### ISSUE TITLE
unpack(): Type C: not enough input, need 1, have 0

### ISSUE THREAD

**Issue by phackwer** [phpseclib/phpseclib#1089]
The issue reported at:

https://github.com/phpseclib/phpseclib/issues/400 and
https://github.com/phpseclib/phpseclib/issues/478

Is happening consistently to us, as the log bellow shows (obs: I copied the piece of code that calls it - BTW, a lot of CTRL+C, CTRL+V). We could not figure it out exactly what is happening, but seems like a network issue, and not a code problem, but we could not debug that deeply enough.

Bellow are the logs we had and the code calls on SSH2.php

[2017-02-01 13:03:14] production.ERROR: ErrorException: unpack(): Type C: not enough input, need 1, have 0 in ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1610
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unpack(): Type ...', '///REALPATHHIDDEN////...', 1610, Array)
#1 ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1610): unpack('Ctype', '')

        $response = $this->_get_binary_packet();

        if ($response === false) {
            user_error('Connection closed by server');
            return false;
        }

1610:        extract(unpack('Ctype', $this->_string_shift($response, 1)));

[2017-02-01 13:10:46] production.ERROR: ErrorException: unpack(): Type C: not enough input, need 1, have 0 in ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1940
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unpack(): Type ...', '///REALPATHHIDDEN////...', 1940, Array)
#1 ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1940): unpack('Ctype', '')

        $response = $this->_get_binary_packet();

        if ($response === false) {
            user_error('Connection closed by server');
            return false;
        }

1940:        extract(unpack('Ctype', $this->_string_shift($response, 1)));

[2017-02-01 13:14:59] production.ERROR: ErrorException: unpack(): Type C: not enough input, need 1, have 0 in ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1521
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unpack(): Type ...', '///REALPATHHIDDEN////...', 1521, Array)
#1 ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1521): unpack('Ctype', '')

[2017-02-01 13:24:24] production.ERROR: ErrorException: unpack(): Type C: not enough input, need 1, have 0 in ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1521
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unpack(): Type ...', '///REALPATHHIDDEN////...', 1521, Array)
#1 ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1521): unpack('Ctype', '')

[2017-02-01 13:27:04] production.ERROR: ErrorException: unpack(): Type C: not enough input, need 1, have 0 in ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1521
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unpack(): Type ...', '///REALPATHHIDDEN////...', 1521, Array)
#1 ///REALPATHHIDDEN/////vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1521): unpack('Ctype', '')

        $response = $this->_get_binary_packet();

        if ($response === false) {
            user_error('Connection closed by server');
            return false;
        }

1521:        extract(unpack('Ctype', $this->_string_shift($response, 1)));

**Comment by terrafrost** [comment]
Try the latest git version. phpseclib should suppress these kinds of errors as of #1064

**Comment by phackwer** [comment]
Supressing may not be enough. We are experiencing some "hangings". We are running a script from CLI that uses the SFTP storage on Laravel, and that calls this library (the only that throws errors on our production server). 

Does anybody else experience scripts hanging (they just keep running forever like if they were reading a null value that triggers no error).

**Comment by terrafrost** [comment]
Post the log files. phpseclib limits them, by default, to 1mb. You can get them by doing `define('NET_SSH2_LOGGING', 2)` at the top and then `$ssh->getLog()` when you get that error. Maybe what you could do is write an error handler that, whenever that kind of error is "caught", the log file is generated. Then, once you have the log file, post it on pastebin.org.
