### ISSUE TITLE
Undefined offset: 256 in SFTP.php on line 434

### ISSUE THREAD

**Issue by NeilStrickland** [phpseclib/phpseclib#1277]
I am using phpseclib version 2.0.11.  The relevant lines in my PHP code are just like this:
```
define('NET_SSH2_LOGGING',2);
$sftp = new \phpseclib\Net\SFTP($hostname);
$sftp->login($user,$pass);
```
I am getting the following messages from $sftp->login():

```
Notice: Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 434
Notice: Unable to fulfill channel request in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3741
Notice: Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3957
Notice: Connection closed prematurely in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3217
Notice: Connection closed by server in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3587
Notice: Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3969
Notice: Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3970
Notice: Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3977
Notice: Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3981
Notice: Connection closed prematurely in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3821
```

Output from $sftp->getLog() is in the attached file:
[sftp_issue.txt](https://github.com/phpseclib/phpseclib/files/2038875/sftp_issue.txt)

Some context: the relevant code has been running as an hourly cron job for years.
It only started generating this error a few hours ago.  It seems likely that something has
changed with the SFTP server at the other end, which I do not control.  However, I am
able to use the server via a desktop SFTP client, so it is not completely dead, although
the performance seems worse than it used to be.  Even if the problem is solely the 
fault of the server, it would be nice to have more informative diagnostics from 
phpseclib.

**Comment by terrafrost** [comment]
Looks like the same issue as described in #1271.  The latest git version should fix the issue for you provided you do this:

```php
$sftp = new \phpseclib\Net\SFTP(...);
$sftp->setTimeout(0);
$sftp->login('user', 'pass');

print_r($sftp->nlist());
```

The problem is here:

```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0003, network: 0.0001s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:01:00:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 9.9948, network: 0.0001s)
00000000  00:00:00:00:00:00:00:09:73:75:62:73:79:73:74:65  ........subsyste
00000010  6d:01:00:00:00:04:73:66:74:70                    m.....sftp

<- NET_SSH2_MSG_GLOBAL_REQUEST (since last: 0.3609, network: 0.0002s)
00000000  00:00:00:17:68:6f:73:74:6b:65:79:73:2d:30:30:40  ....hostkeys-00@
00000010  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:01:17  openssh.com.....
00000020  00:00:00:07:73:73:68:2d:72:73:61:00:00:00:03:01  ....ssh-rsa.....
00000030  00:01:00:00:01:01:00:d0:2d:81:d7:54:cc:e5:1f:50  ........-..T...P
00000040  b6:22:3e:7c:b9:fc:bf:dd:94:63:d3:51:bf:de:23:e1  .">|.....c.Q..#.
00000050  a4:c1:5d:15:c6:0a:05:d7:bf:90:c3:01:1a:69:c5:c6  ..]..........i..
00000060  1e:70:87:f5:18:a8:89:4e:dc:b0:8f:70:ee:e1:3d:8e  .p.....N...p..=.
00000070  19:ba:39:2f:1e:1e:36:09:32:67:bf:28:58:61:77:e2  ..9/..6.2g.(Xaw.
00000080  e4:0c:fc:da:df:51:9f:b6:c3:f7:04:01:38:c3:c6:2f  .....Q......8../
00000090  43:be:e4:9a:b1:87:1f:1f:29:1c:ba:05:94:bc:53:20  C.......).....S 
000000a0  e0:6c:4b:b5:f0:bf:1c:93:55:4f:f8:82:c7:4f:75:dc  .lK.....UO...Ou.
000000b0  b1:6a:aa:50:2b:09:da:12:a9:2b:a1:2d:8c:d4:bb:a7  .j.P+....+.-....
000000c0  9f:ac:b8:2d:d9:91:53:8b:2d:5f:50:d0:63:6f:44:77  ...-..S.-_P.coDw
000000d0  f2:eb:c3:f8:96:62:ef:5f:74:8d:b7:1a:9c:0a:e1:78  .....b._t......x
000000e0  85:e6:91:a2:ae:6c:2a:8c:e0:ae:4a:c2:c9:0a:4d:4b  .....l*...J...MK
000000f0  b6:dc:f1:f5:6a:9c:09:ea:da:36:43:5d:3b:7d:49:7f  ....j....6C];}I.
00000100  52:09:60:42:75:11:d2:9d:22:17:f2:ef:11:44:c5:e3  R.`Bu..."....D..
00000110  99:d8:7a:6e:3d:e3:54:b9:57:82:4d:22:25:17:df:cb  ..zn=.T.W.M"%...
00000120  c0:1e:ca:ed:a3:4c:af:b9:cc:a2:06:27:6b:94:4e:1f  .....L.....'k.N.
00000130  c4:e8:f9:b6:2c:fd:e3:00:00:00:68:00:00:00:13:65  ....,.....h....e
00000140  63:64:73:61:2d:73:68:61:32:2d:6e:69:73:74:70:32  cdsa-sha2-nistp2
00000150  35:36:00:00:00:08:6e:69:73:74:70:32:35:36:00:00  56....nistp256..
00000160  00:41:04:62:48:5f:08:38:ba:32:66:1e:13:83:0e:06  .A.bH_.8.2f.....
00000170  1a:2c:16:a4:14:61:a8:f6:ce:4a:03:9e:45:cf:bc:72  .,...a...J..E..r
00000180  93:cb:37:90:6b:cb:b3:de:d1:01:ab:f0:2d:03:49:70  ..7.k.......-.Ip
00000190  ce:e4:85:d5:b4:0a:0b:35:df:ad:e3:4c:01:36:57:6a  .......5...L.6Wj
000001a0  e4:3a:35:00:00:00:33:00:00:00:0b:73:73:68:2d:65  .:5...3....ssh-e
000001b0  64:32:35:35:31:39:00:00:00:20:bb:82:41:ed:9d:90  d25519... ..A...
000001c0  74:6e:37:e0:07:99:f2:af:89:65:51:8a:70:64:04:b3  tn7......eQ.pd..
000001d0  ba:10:51:6b:b6:86:16:27:aa:84                    ..Qk...'..
```

phpseclib sends a NET_SSH2_MSG_CHANNEL_OPEN packet. The server responds with a NET_SSH2_MSG_GLOBAL_REQUEST packet but the response times out so phpseclib then sends the next packet - a NET_SSH2_MSG_CHANNEL_REQUEST packet - before it has gotten the appropriate response. It then errors out.

In the case of #1271, when setting the timeout to zero (and using the latest Git version) it wound up taking the server 25s to respond. This delay affected other SFTP / SSH clients as well and was not exlusive to phpseclib. Quoting #1271,

> Upon sticking a `strace` on the relevant `sshd` process, revealed that I had a problem with `systemd-logind` needing restarting after a certain other service has been restarted: https://serverfault.com/questions/707377/slow-ssh-login-activation-of-org-freedesktop-login1-timed-out.

**Comment by NeilStrickland** [comment]
Many thanks for your help, which is much appreciated.  

After installing the latest Git version (and updating a whole cascade of other stuff to support it, hence the delay) the error has gone away.  As with #1271, the server is taking about 25 seconds to handle the login. 

I should perhaps mention that if I do not set a timeout of zero, then I now get a fatal error as follows:

```
Notice:  Undefined offset: 256 in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 438

Fatal error:  Uncaught RuntimeException: Unable to fulfill channel request in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3799
Stack trace:
#0 /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(451): phpseclib\Net\SSH2->get_channel_packet(256, true)
#1 /var/www/somas/admin/manager/ms.php(28): phpseclib\Net\SFTP->login('****', '*****')
#2 {main}
  thrown in /var/www/somas/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3799
```
This should presumably be trapped.

**Comment by terrafrost** [comment]
> I should perhaps mention that if I do not set a timeout of zero, then I now get a fatal error as follows:

Are you using the master branch? You shouldn't be. The master branch has an unstable API. ie. I may, from commit to commit make BC breaking changes with the API. You should be using the 2.0 branch.

That said, yah, the master branch throws exceptions and that's not behavior I have any current plans on changing. If you want to suppress the error you can wrap the code around a try / catch block.

And the reason it's throwing an exception is because it's not getting a response when it expects one. It sends a NET_SSH2_MSG_CHANNEL_REQUEST packet and expects to get a packet back and when it doesn't - at least not within the timeout period - that is a legit error state in-so-far as phpseclib is concerned.
