### ISSUE TITLE
unpack(): Type C: not enough input, need 1, have 0

### ISSUE THREAD

**Issue by cabloo** [phpseclib/phpseclib#1302]
Seeing an exception during authentication to a Dell PowerConnect switch:

```
unpack(): Type C: not enough input, need 1, have 0
```

I updated to latest composer version, v2.0.11, and still receiving this error. Log & Stack trace below.

Log:
```
<-
00000000  53:53:48:2d:31:2e:39:39:2d:4f:70:65:6e:53:53:48  SSH-1.99-OpenSSH
00000010  5f:34:2e:33:0a                                   _4.3.

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:29:0d  b_2.0 (openssl).
00000020  0a                                               .

<- NET_SSH2_MSG_KEXINIT (since last: 3.1493, network: 0.0654s)
00000000  b2:77:2b:76:55:98:a2:7e:78:43:a0:02:10:cd:8c:30  .w+vU..~xC.....0
00000010  00:00:00:59:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...Ydiffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67  an-group-exchang
00000030  65:2d:73:68:61:31:2c:64:69:66:66:69:65:2d:68:65  e-sha1,diffie-he
00000040  6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:34:2d:73:68  llman-group14-sh
00000050  61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61  a1,diffie-hellma
00000060  6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:00:00:00  n-group1-sha1...
00000070  0f:73:73:68:2d:72:73:61:2c:73:73:68:2d:64:73:73  .ssh-rsa,ssh-dss
00000080  00:00:00:9d:61:65:73:31:32:38:2d:63:62:63:2c:33  ....aes128-cbc,3
00000090  64:65:73:2d:63:62:63:2c:62:6c:6f:77:66:69:73:68  des-cbc,blowfish
000000a0  2d:63:62:63:2c:63:61:73:74:31:32:38:2d:63:62:63  -cbc,cast128-cbc
000000b0  2c:61:72:63:66:6f:75:72:31:32:38:2c:61:72:63:66  ,arcfour128,arcf
000000c0  6f:75:72:32:35:36:2c:61:72:63:66:6f:75:72:2c:61  our256,arcfour,a
000000d0  65:73:31:39:32:2d:63:62:63:2c:61:65:73:32:35:36  es192-cbc,aes256
000000e0  2d:63:62:63:2c:72:69:6a:6e:64:61:65:6c:2d:63:62  -cbc,rijndael-cb
000000f0  63:40:6c:79:73:61:74:6f:72:2e:6c:69:75:2e:73:65  c@lysator.liu.se
00000100  2c:61:65:73:31:32:38:2d:63:74:72:2c:61:65:73:31  ,aes128-ctr,aes1
00000110  39:32:2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74  92-ctr,aes256-ct
00000120  72:00:00:00:9d:61:65:73:31:32:38:2d:63:62:63:2c  r....aes128-cbc,
00000130  33:64:65:73:2d:63:62:63:2c:62:6c:6f:77:66:69:73  3des-cbc,blowfis
00000140  68:2d:63:62:63:2c:63:61:73:74:31:32:38:2d:63:62  h-cbc,cast128-cb
00000150  63:2c:61:72:63:66:6f:75:72:31:32:38:2c:61:72:63  c,arcfour128,arc
00000160  66:6f:75:72:32:35:36:2c:61:72:63:66:6f:75:72:2c  four256,arcfour,
00000170  61:65:73:31:39:32:2d:63:62:63:2c:61:65:73:32:35  aes192-cbc,aes25
00000180  36:2d:63:62:63:2c:72:69:6a:6e:64:61:65:6c:2d:63  6-cbc,rijndael-c
00000190  62:63:40:6c:79:73:61:74:6f:72:2e:6c:69:75:2e:73  bc@lysator.liu.s
000001a0  65:2c:61:65:73:31:32:38:2d:63:74:72:2c:61:65:73  e,aes128-ctr,aes
000001b0  31:39:32:2d:63:74:72:2c:61:65:73:32:35:36:2d:63  192-ctr,aes256-c
000001c0  74:72:00:00:00:55:68:6d:61:63:2d:6d:64:35:2c:68  tr...Uhmac-md5,h
000001d0  6d:61:63:2d:73:68:61:31:2c:68:6d:61:63:2d:72:69  mac-sha1,hmac-ri
000001e0  70:65:6d:64:31:36:30:2c:68:6d:61:63:2d:72:69:70  pemd160,hmac-rip
000001f0  65:6d:64:31:36:30:40:6f:70:65:6e:73:73:68:2e:63  emd160@openssh.c
00000200  6f:6d:2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c  om,hmac-sha1-96,
00000210  68:6d:61:63:2d:6d:64:35:2d:39:36:00:00:00:55:68  hmac-md5-96...Uh
00000220  6d:61:63:2d:6d:64:35:2c:68:6d:61:63:2d:73:68:61  mac-md5,hmac-sha
00000230  31:2c:68:6d:61:63:2d:72:69:70:65:6d:64:31:36:30  1,hmac-ripemd160
00000240  2c:68:6d:61:63:2d:72:69:70:65:6d:64:31:36:30:40  ,hmac-ripemd160@
00000250  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
00000260  2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d:64  -sha1-96,hmac-md
00000270  35:2d:39:36:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69  5-96....none,zli
00000280  62:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00  b@openssh.com...
00000290  15:6e:6f:6e:65:2c:7a:6c:69:62:40:6f:70:65:6e:73  .none,zlib@opens
000002a0  73:68:2e:63:6f:6d:00:00:00:00:00:00:00:00:00:00  sh.com..........
000002b0  00:00:00                                         ...

-> NET_SSH2_MSG_KEXINIT (since last: 0.0096, network: 0s)
00000000  2b:5a:ed:cf:3f:f7:87:be:23:5f:95:e9:8a:65:4f:eb  +Z..?...#_...eO.
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  56....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:e9:61:72:63:66:6f:75:72  h-dss....arcfour
000000b0  32:35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61  256,arcfour128,a
000000c0  65:73:31:32:38:2d:63:74:72:2c:61:65:73:31:39:32  es128-ctr,aes192
000000d0  2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c  -ctr,aes256-ctr,
000000e0  74:77:6f:66:69:73:68:31:32:38:2d:63:74:72:2c:74  twofish128-ctr,t
000000f0  77:6f:66:69:73:68:31:39:32:2d:63:74:72:2c:74:77  wofish192-ctr,tw
00000100  6f:66:69:73:68:32:35:36:2d:63:74:72:2c:61:65:73  ofish256-ctr,aes
00000110  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
00000120  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:74:77  bc,aes256-cbc,tw
00000130  6f:66:69:73:68:31:32:38:2d:63:62:63:2c:74:77:6f  ofish128-cbc,two
00000140  66:69:73:68:31:39:32:2d:63:62:63:2c:74:77:6f:66  fish192-cbc,twof
00000150  69:73:68:32:35:36:2d:63:62:63:2c:74:77:6f:66:69  ish256-cbc,twofi
00000160  73:68:2d:63:62:63:2c:62:6c:6f:77:66:69:73:68:2d  sh-cbc,blowfish-
00000170  63:74:72:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63  ctr,blowfish-cbc
00000180  2c:33:64:65:73:2d:63:74:72:2c:33:64:65:73:2d:63  ,3des-ctr,3des-c
00000190  62:63:00:00:00:e9:61:72:63:66:6f:75:72:32:35:36  bc....arcfour256
000001a0  2c:61:72:63:66:6f:75:72:31:32:38:2c:61:65:73:31  ,arcfour128,aes1
000001b0  32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74  28-ctr,aes192-ct
000001c0  72:2c:61:65:73:32:35:36:2d:63:74:72:2c:74:77:6f  r,aes256-ctr,two
000001d0  66:69:73:68:31:32:38:2d:63:74:72:2c:74:77:6f:66  fish128-ctr,twof
000001e0  69:73:68:31:39:32:2d:63:74:72:2c:74:77:6f:66:69  ish192-ctr,twofi
000001f0  73:68:32:35:36:2d:63:74:72:2c:61:65:73:31:32:38  sh256-ctr,aes128
00000200  2d:63:62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c  -cbc,aes192-cbc,
00000210  61:65:73:32:35:36:2d:63:62:63:2c:74:77:6f:66:69  aes256-cbc,twofi
00000220  73:68:31:32:38:2d:63:62:63:2c:74:77:6f:66:69:73  sh128-cbc,twofis
00000230  68:31:39:32:2d:63:62:63:2c:74:77:6f:66:69:73:68  h192-cbc,twofish
00000240  32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73:68:2d  256-cbc,twofish-
00000250  63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:74:72  cbc,blowfish-ctr
00000260  2c:62:6c:6f:77:66:69:73:68:2d:63:62:63:2c:33:64  ,blowfish-cbc,3d
00000270  65:73:2d:63:74:72:2c:33:64:65:73:2d:63:62:63:00  es-ctr,3des-cbc.
00000280  00:00:39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  ..9hmac-sha2-256
00000290  2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d  ,hmac-sha1-96,hm
000002a0  61:63:2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35  ac-sha1,hmac-md5
000002b0  2d:39:36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39  -96,hmac-md5...9
000002c0  68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d  hmac-sha2-256,hm
000002d0  61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d  ac-sha1-96,hmac-
000002e0  73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36  sha1,hmac-md5-96
000002f0  2c:68:6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e  ,hmac-md5....non
00000300  65:00:00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00  e....none.......
00000310  00:00:00:00:00:00                                ......

-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0126, network: 0s)
00000000  00:00:00:81:00:85:e4:62:1b:99:54:e7:66:24:a1:7f  .......b..T.f$..
00000010  df:1d:60:b7:35:30:fb:a8:c5:1f:53:ed:85:85:a4:e7  ..`.50....S.....
00000020  2b:36:45:60:34:64:e4:f8:a3:a5:c4:72:cf:eb:fd:29  +6E`4d.....r...)
00000030  d5:b3:1f:37:c4:b4:25:b1:d6:19:6b:fd:3c:25:e9:46  ...7..%...k..%.F
00000040  8e:2b:dd:d4:98:8a:2a:54:28:ba:c0:b0:61:7f:c7:d4  .+....*T(...a...
00000050  c4:e2:d8:b2:61:18:57:cd:75:7b:9a:81:b2:92:c6:fe  ....a.W.u{......
00000060  89:65:bc:db:90:f5:cc:b0:0c:c8:f9:80:17:aa:97:2e  .e..............
00000070  8b:ee:98:6e:73:00:ad:a0:cf:79:a7:e5:6c:0c:b9:ff  ...ns....y..l...
00000080  a0:45:d0:ef:81                                   .E...
```

Stack trace:
```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unpack(): Type ...', '/var/www/html/v...', 1521, Array)
#1 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1521): unpack('Ctype', '')
#2 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1115): phpseclib\Net\SSH2->_key_exchange('\x14\xB2w+vU\x98\xA2~xC\xA0\x02\x10\xCD...')
#3 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1888): phpseclib\Net\SSH2->_connect()
#4 [internal function]: phpseclib\Net\SSH2->_login('*****', '******')
#5 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1872): call_user_func_array(Array, Array)
#6 /var/www/html/app/Control/Ssh/Connection.php(187): phpseclib\Net\SSH2->login('****', '****')
```

**Comment by terrafrost** [comment]
This is just a guess but I wonder if `$ssh->sendKEXINITLast()` would do the trick.

**Comment by terrafrost** [comment]
I guess the `ssh -vvv` output couldn't hurt but what'd be more useful is the PuTTY logs.  You can get them by going to PuTTY->Session->Logging and checking the "SSH packets" radio button.

Failing that, giving me access to the server might help. If that would be do'able you could send auth info to terrafrost@php.net.

**Comment by cabloo** [comment]
Here is the ssh -vvv output. I am traveling right now so only have my Linux
laptop, I can provide Putty debug output when I get back to my desktop at
home. Unfortunately, I cannot send access details since it is a switch that
is in use in production. Thanks for looking into this!

```
OpenSSH_6.7p1 Debian-5+deb8u4, OpenSSL 1.0.1t  3 May 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to ****** [*****] port 911.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u4
debug1: Remote protocol version 1.99, remote software version OpenSSH_4.3
debug1: match: OpenSSH_4.3 pat OpenSSH_4* compat 0x00000000
debug2: fd 3 setting O_NONBLOCK
debug3: put_host_port: [*****]:911
debug3: load_hostkeys: loading entries for host "[*****]:911" from file
"/root/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /root/.ssh/known_hosts:5
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-rsa-cert-v01@openssh.com,
ssh-rsa-cert-v00@openssh.com,ssh-rsa
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org
,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,
ssh-rsa-cert-v00@openssh.com,ssh-rsa,
ecdsa-sha2-nistp256-cert-v01@openssh.com,
ecdsa-sha2-nistp384-cert-v01@openssh.com,
ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,
ssh-dss-cert-v01@openssh.com,ssh-dss-cert-v00@openssh.com
,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,
aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,
rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,
aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,
rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,
hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,
hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com
,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,
hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,
hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,
hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,
hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,
hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com
,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,
hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,
hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,
hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit:
diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss
debug2: kex_parse_kexinit:
aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour128,arcfour256,arcfour,aes192-cbc,aes256-cbc,
rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
debug2: kex_parse_kexinit:
aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour128,arcfour256,arcfour,aes192-cbc,aes256-cbc,
rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,hmac-ripemd160,
hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,hmac-ripemd160,
hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: mac_setup: setup hmac-sha1
debug1: kex: server->client aes128-ctr hmac-sha1 none
debug2: mac_setup: setup hmac-sha1
debug1: kex: client->server aes128-ctr hmac-sha1 none
debug2: bits set: 1035/2048
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Server host key: RSA 3d:05:d5:ae:24:9a:48:9b:4b:82:65:b8:bd:d1:4d:83
debug3: put_host_port: [*****]:911
debug3: put_host_port: [*****]:911
debug3: load_hostkeys: loading entries for host "[*****]:911" from file
"/root/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /root/.ssh/known_hosts:5
debug3: load_hostkeys: loaded 1 keys
debug3: load_hostkeys: loading entries for host "[*****]:911" from file
"/root/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /root/.ssh/known_hosts:5
debug3: load_hostkeys: loaded 1 keys
debug1: Host '[*****]:911' is known and matches the RSA host key.
debug1: Found key in /root/.ssh/known_hosts:5
debug2: bits set: 1008/2048
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /root/.ssh/id_rsa ((nil)),
debug2: key: /root/.ssh/id_dsa ((nil)),
debug2: key: /root/.ssh/id_ecdsa ((nil)),
debug2: key: /root/.ssh/id_ed25519 ((nil)),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred
gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug3: no such identity: /root/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
admin@*****'s password:
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to ***** ([*****]:911).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Entering interactive session.
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug1: Sending environment.
debug3: Ignored env SHELL
debug3: Ignored env TERM
debug3: Ignored env USER
debug3: Ignored env MAIL
debug3: Ignored env PATH
debug3: Ignored env PWD
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env SHLVL
debug3: Ignored env HOME
debug3: Ignored env LOGNAME
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 131072
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
```

**Comment by terrafrost** [comment]
I just saw this. I'll try to take a look, if not this evening then probably over the weekend.

Thanks!

**Comment by terrafrost** [comment]
The problem is that phpseclib is sending a NET_SSH2_MSG_KEXDH_INIT packet and isn't getting a response.

I note PuTTY is sending a SSH2_MSG_KEX_DH_GEX_REQUEST packet instead of the NET_SSH2_MSG_KEXDH_INIT packet that phpseclib is sending. This makes me wonder if doing this would help:

```
#
#-----[ FIND ]------------------------------------------
#
        $kex_algorithms = array(
            // Elliptic Curve Diffie-Hellman Key Agreement (ECDH) using
            // Curve25519. See doc/curve25519-sha256@libssh.org.txt in the
            // libssh repository for more information.
            'curve25519-sha256@libssh.org',
            // Diffie-Hellman Key Agreement (DH) using integer modulo prime
            // groups.
            'diffie-hellman-group1-sha1', // REQUIRED
            'diffie-hellman-group14-sha1', // REQUIRED
            'diffie-hellman-group-exchange-sha1', // RFC 4419
            'diffie-hellman-group-exchange-sha256', // RFC 4419
        );
#
#-----[ REPLACE WITH ]----------------------------------
#
        $kex_algorithms = array(
            // Elliptic Curve Diffie-Hellman Key Agreement (ECDH) using
            // Curve25519. See doc/curve25519-sha256@libssh.org.txt in the
            // libssh repository for more information.
            'curve25519-sha256@libssh.org',
            // Diffie-Hellman Key Agreement (DH) using integer modulo prime
            // groups.
            'diffie-hellman-group-exchange-sha1', // RFC 4419
            'diffie-hellman-group-exchange-sha256', // RFC 4419
            'diffie-hellman-group1-sha1', // REQUIRED
            'diffie-hellman-group14-sha1', // REQUIRED
        );
```

ie. make it so phpseclib preferentially uses diffie-hellman-group-exchange-sha1 instead of diffie-hellman-group1-sha1.

It _shouldn't_ matter. If the server is gonna claim it supports the algorithm in question it _ought_ to. But it is, none-the-less, possible that it doesn't.

**Comment by cabloo** [comment]
This seems to be the issue: 

https://superuser.com/a/597956/435293

I don't think this is a problem specifically with this library - it just supports a lot of methods so therefore sends some larger packets which causes issues when routing through some firewalls due to MTU fragmentation.

Thanks again for all the help!

**Comment by cabloo** [comment]
This seems to be the issue: 

https://superuser.com/a/597956/435293

I don't think this is a problem specifically with this library - it just supports a lot of methods so therefore sends some larger packets which causes issues when routing through some firewalls due to MTU fragmentation.

Thanks again for all the help!
