### ISSUE TITLE
fatal error - Invalid size

### ISSUE THREAD

**Issue by N3XT0R** [phpseclib/phpseclib#1545]
Hello Guys, 
i am using the latest version of your package (2.0.29). 
Actually on bigger downloads (ca. 600 MB) through an sftp connection i am getting a fatal with "invalid size" as message, it looks like a bug: 

`
[2020-11-20 18:17:49] local.ERROR: Invalid size {"exception":"[object] (ErrorException(code: 0): Invalid size at /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3360)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(1024, 'Invalid size', '/var/www/html/v...', 3360, Array)
#1 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3360): user_error('Invalid size')
#2 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1430): phpseclib\\Net\\SSH2->_get_binary_packet()
#3 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1288): phpseclib\\Net\\SSH2->_key_exchange()
#4 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2152): phpseclib\\Net\\SSH2->_connect()
#5 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2129): phpseclib\\Net\\SSH2->_login('username')
#6 [internal function]: phpseclib\\Net\\SSH2->login('username', Object(phpseclib\\Crypt\\RSA))
#7 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(425): call_user_func_array('parent::login', Array)
#8 /var/www/html/vendor/laravelcollective/remote/src/SecLibGateway.php(98): phpseclib\\Net\\SFTP->login('username', Object(phpseclib\\Crypt\\RSA))
#9 /var/www/html/vendor/laravelcollective/remote/src/Connection.php(142): Collective\\Remote\\SecLibGateway->connect('username')
#10 /var/www/html/vendor/laravelcollective/remote/src/Connection.php(231): Collective\\Remote\\Connection->getGateway()
[.....]
`

**Comment by terrafrost** [comment]
Can you post your servers identification string? You can get it by doing `$ssh->getServerIdentification()`? Also, if you could do `$ssh->getAlgorithmsNegotiated()` and post the results that'd be cool.

Thanks!

**Comment by N3XT0R** [comment]
Hey,
yes i can post that information here:

ServerIdent: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8

AlgorithmsNegotiated:

[0] => Array
                (
                    [kex] => curve25519-sha256@libssh.org
                    [hostkey] => rsa-sha2-256
                    [client_to_server] => Array
                        (
                            [crypt] => aes128-ctr
                            [mac] => hmac-sha2-256
                            [comp] => none
                        )

                    [server_to_client] => Array
                        (
                            [crypt] => aes128-ctr
                            [mac] => hmac-sha2-256
                            [comp] => none
                        )

                )

**Comment by terrafrost** [comment]
Can you get me SFTP access? You could email the credentials and host name to terrafrost@php.net. This would enable me to reproduce the issue, at which point, I could then work on a fix.

If getting me SFTP access isn't an option then could you post the simple logs? You can get them by doing `define('NET_SSH2_LOGGING', 1);` at the top of the file and then `echo $ssh->getLog();` after where ever you encounter the error. What I'm wondering is if you're getting that error after key re exchange.

**Comment by terrafrost** [comment]
Closing due to inactivity
