### ISSUE TITLE
Is it possible to generate id-RSASSA-PSS keys with phpseclib?

### ISSUE THREAD

**Issue by itsrachelfish** [phpseclib/phpseclib#1628]
I am a new user following the documentation and I cannot figure out how to generate a RSA-PSS key with phpseclib. I have created this simple demo which writes a private key to a file:

```
$private = RSA::createKey();
file_put_contents("private.key", $private);
```

Then, in another file I am trying to read the key:

```
$private = RSA::loadFormat('PSS', file_get_contents('./private.key'));
```

But this gives me the error:

```
PHP Fatal error:  Uncaught phpseclib3\Exception\UnsupportedAlgorithmException: Only id-RSASSA-PSS keys are supported; this is a 1.2.840.113549.1.1.1 key in ./testing/php/crypto/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/Formats/Keys/PKCS8.php:460
Stack trace:
#0 ./testing/php/crypto/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA/Formats/Keys/PSS.php(117): phpseclib3\Crypt\Common\Formats\Keys\PKCS8::load('0\x82\tD\x02\x01\x000\r\x06\t*\x86H\x86...', false)
#1 ./testing/php/crypto/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php(248): phpseclib3\Crypt\RSA\Formats\Keys\PSS::load('-----BEGIN PRIV...', false)
#2 ./testing/php/crypto/sign.php(7): phpseclib3\Crypt\Common\AsymmetricKey::loadFormat('PSS', '-----BEGIN PRIV...')
#3 {main}
  thrown in ./testing/php/crypto/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/Formats/Keys/PKCS8.php on line 460
```

However, if I generate the key with openssl on the command line it works:

```
openssl genpkey -algorithm rsa-pss > private.key 
```

I found this note while reading the source:

https://github.com/phpseclib/phpseclib/blob/b296d4a88b41dca4bbdfde2980c1234563751344/phpseclib/Crypt/RSA.php#L40-L46

But I could not find any further documentation relating to the generation of id-RSASSA-PSS keys.

**Comment by itsrachelfish** [comment]
I read the source code harder and it looks like the solution is to pass the "PSS" type to the `toString` function.

```
file_put_contents("private.key", $private->toString('PSS'));
```

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA/PrivateKey.php#L495-L527

:sweat_smile:
