### ISSUE TITLE
Nexans : "Unable to open channel" : type 94 is unknown

### ISSUE THREAD

**Issue by dominiquefournier** [phpseclib/phpseclib#1631]
Hi 
I try to connect to Nexans microswitch and I have the "Unable to open channel" exception.
My code is : 
```
<?php
use phpseclib3\Net\SSH2;

require_once ("vendor/autoload.php");

$ssh = new SSH2('192.168.255.165', 22);
if (!$ssh->login('admin', 'nexans')) {
    throw new \Exception('Login failed');
}
define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX);
$output = $ssh->read('~#~', SSH2::READ_REGEX);
echo $ssh->getLog();
```
The error is : 
```
PHP Fatal error:  Uncaught RuntimeException: Unable to open channel in /home/fournier/Programmation/PHP/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3823
Stack trace:
#0 /home/fournier/Programmation/PHP/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3529): phpseclib3\Net\SSH2->get_channel_packet(true)
#1 /home/fournier/Programmation/PHP/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3401): phpseclib3\Net\SSH2->filter('^\x00\x00\x00\x02\x00\x00\x01\x8F\r\nEnte...', false)
#2 /home/fournier/Programmation/PHP/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2783): phpseclib3\Net\SSH2->get_binary_packet()
#3 /home/fournier/Programmation/PHP/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2919): phpseclib3\Net\SSH2->initShell()
#4 /home/fournier/Programmation/PHP/phpseclib/test.php(11): phpseclib3\Net\SSH2->read('~#~', 2)
#5 {main}
  thrown in /home/fournier/Programmation/PHP/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3823
```

I update the phpseclib code to display the $type : it is 94, which is not managed by phpseclib.

I add a new case in vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php (line 3819) : 
```
   case 94:
         return false;
``` 
it remove the exception, and see the trace (but I don't know if it is what it is needed to do) : 
```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.6647, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:02:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0279, network: 0.0001s)
00000000  00:00:00:02:00:00:00:2b:00:00:7d:00:00:00:88:b8  .......+..}.....

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0003, network: 0.0001s)
00000000  00:00:00:2b:00:00:00:07:70:74:79:2d:72:65:71:01  ...+....pty-req.
00000010  00:00:00:05:76:74:31:30:30:00:00:00:50:00:00:00  ....vt100...P...
00000020  18:00:00:00:00:00:00:00:00:00:00:00:01:00        ..............

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0229, network: 0.0228s)
00000000  00:00:00:02:00:00:01:8f:0d:0a:45:6e:74:65:72:20  ..........Enter 
00000010  63:6f:6d:6d:61:6e:64:20:27:3f:27:20:6f:72:20:27  command '?' or '
00000020  68:65:6c:70:20:5b:6b:65:79:2d:77:6f:72:64:5d:20  help [key-word] 
00000030  5b:6b:65:79:2d:77:6f:72:64:5d:27:20:74:6f:20:73  [key-word]' to s
00000040  65:61:72:63:68:20:63:6f:6d:6d:61:6e:64:73:2e:0d  earch commands..
00000050  0a:45:78:61:6d:70:6c:65:73:3a:0d:0a:20:3f:20:20  .Examples:.. ?  
00000060  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20                  
00000070  20:2d:20:4c:69:73:74:73:20:73:68:6f:72:74:20:64   - Lists short d
00000080  65:73:63:72:69:70:74:69:6f:6e:20:6f:66:20:61:6c  escription of al
00000090  6c:20:63:6f:6d:6d:61:6e:64:73:0d:0a:20:68:65:6c  l commands.. hel
000000a0  70:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  p               
000000b0  20:2d:20:4c:69:73:74:73:20:6c:6f:6e:67:20:64:65   - Lists long de
000000c0  73:63:72:69:70:74:69:6f:6e:20:6f:66:20:61:6c:6c  scription of all
000000d0  20:63:6f:6d:6d:61:6e:64:73:0d:0a:20:68:65:6c:70   commands.. help
000000e0  20:76:6c:61:6e:20:20:20:20:20:20:20:20:20:20:20   vlan           
000000f0  2d:20:4c:69:73:74:73:20:6f:6e:6c:79:20:63:6f:6d  - Lists only com
00000100  6d:61:6e:64:73:20:77:69:74:68:20:6b:65:79:77:6f  mands with keywo
00000110  72:64:20:76:6c:61:6e:0d:0a:20:68:65:6c:70:20:76  rd vlan.. help v
00000120  6c:61:6e:20:69:6e:74:65:72:66:61:63:65:20:2d:20  lan interface - 
00000130  4c:69:73:74:73:20:6f:6e:6c:79:20:63:6f:6d:6d:61  Lists only comma
00000140  6e:64:73:20:77:69:74:68:20:6b:65:79:77:6f:72:64  nds with keyword
00000150  20:76:6c:61:6e:20:61:6e:64:20:69:6e:74:65:72:66   vlan and interf
00000160  61:63:65:0d:0a:0d:0a:46:54:54:4f:2d:43:31:2d:41  ace....FTTO-C1-A
00000170  2d:42:44:5a:32:2d:6e:61:2d:31:33:2d:31:34:2d:43  -BDZ2-na-13-14-C
00000180  31:2d:31:30:36:2e:67:72:65:6e:6f:62:6c:65:2e:63  1-106.grenoble.c
00000190  6e:72:73:2e:66:72:23                             nrs.fr#

<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.072, network: 0.0719s)
00000000  00:00:00:02                                      ....

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0003, network: 0.0001s)
00000000  00:00:00:2b:00:00:00:05:73:68:65:6c:6c:01        ...+....shell.

<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0235, network: 0.0001s)
00000000  00:00:00:02    
```
It generate the trace after a timeout, and the $output value is ""

Of course, with ssh, no problem : 
```
$ ssh admin@192.168.255.165
admin@192.168.255.165's password: 

Enter command '?' or 'help [key-word] [key-word]' to search commands.
Examples:
 ?                   - Lists short description of all commands
 help                - Lists long description of all commands
 help vlan           - Lists only commands with keyword vlan
 help vlan interface - Lists only commands with keyword vlan and interface

FTTO-C1-A-BDZ2-na-13-14-C1-106.grenoble.cnrs.fr#
```

Could you add this new 94 type ? If I read https://tools.ietf.org/html/rfc4250#section-4.1.2, it should be "SSH_MSG_CHANNEL_DATA"
Thanks

**Comment by terrafrost** [comment]
[Line 3823](https://github.com/phpseclib/phpseclib/blob/3.0.6/phpseclib/Net/SSH2.php#L3823) is a `break` statement so that line number isn't super useful. BUT thankfully there's only one line that throws an "Unable to open channel" exception and that'd be [line 3821](https://github.com/phpseclib/phpseclib/blob/3.0.6/phpseclib/Net/SSH2.php#L3821).

Anyway, what I can tell you is that SSH_MSG_CHANNEL_DATA is most definitely supported. From `send_channel_packet`:

https://github.com/phpseclib/phpseclib/blob/eeabad1ed3cdf91302cd01ec3a4bcf6059e77ffa/phpseclib/Net/SSH2.php#L4125-L4130

From `get_channel_packet`:

https://github.com/phpseclib/phpseclib/blob/eeabad1ed3cdf91302cd01ec3a4bcf6059e77ffa/phpseclib/Net/SSH2.php#L3841-L3842

In so far as your error goes...  that error would lead me to conclude that the issue is that the server isn't responding to your NET_SSH2_MSG_CHANNEL_OPEN request with a NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION response and yet in the SSH logs for your modified version it is:

```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.6647, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:02:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0279, network: 0.0001s)
00000000  00:00:00:02:00:00:00:2b:00:00:7d:00:00:00:88:b8  .......+..}.....
```
So that doesn't make a lot of sense.

If the server _was_ responding with a response of "94" then why isn't it showing up in your modified logs either? Logging is done by `get_binary_packet`:

https://github.com/phpseclib/phpseclib/blob/eeabad1ed3cdf91302cd01ec3a4bcf6059e77ffa/phpseclib/Net/SSH2.php#L3392-L3399

So that doesn't make a lot of sense to me.

Could you get me the SSH2 logs when you _are_ having this issue? The full logs would be ideal as that'd tell me the name of the SSH server you're connecting to as well. Your post mentions Nexans microswitch but the SSH server could be their own home grown one (which would be more likely to be buggy) or OpenSSH (which would be less likely to be buggy).

I'm also kinda wondering if this wasn't maybe a one off issue. ie. if you ran phpseclib again _without_ your changes it'd work.

**Comment by dominiquefournier** [comment]
First, thanks to look at this !

I don't modify the lib source code anymore. I modify my code to catch the exception : 
```
<?php
use phpseclib3\Net\SSH2;

require_once ("vendor/autoload.php");

$ssh = new SSH2('192.168.255.165', 22);
if (!$ssh->login('admin', 'nexans')) {
    throw new \Exception('Login failed');
}
define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX);
try
{
  $output = $ssh->read('~#~', SSH2::READ_REGEX);
}
catch (RuntimeException $e)
{
}
echo $ssh->getLog();
echo $e->getMessage()."\n";
```

Then the log is : 
```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.7973, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:02:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0253, network: 0.0001s)
00000000  00:00:00:02:00:00:00:2b:00:00:7d:00:00:00:88:b8  .......+..}.....

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0003, network: 0.0001s)
00000000  00:00:00:2b:00:00:00:07:70:74:79:2d:72:65:71:01  ...+....pty-req.
00000010  00:00:00:05:76:74:31:30:30:00:00:00:50:00:00:00  ....vt100...P...
00000020  18:00:00:00:00:00:00:00:00:00:00:00:01:00        ..............

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0263, network: 0.0262s)
00000000  00:00:00:02:00:00:01:8f:0d:0a:45:6e:74:65:72:20  ..........Enter 
00000010  63:6f:6d:6d:61:6e:64:20:27:3f:27:20:6f:72:20:27  command '?' or '
00000020  68:65:6c:70:20:5b:6b:65:79:2d:77:6f:72:64:5d:20  help [key-word] 
00000030  5b:6b:65:79:2d:77:6f:72:64:5d:27:20:74:6f:20:73  [key-word]' to s
00000040  65:61:72:63:68:20:63:6f:6d:6d:61:6e:64:73:2e:0d  earch commands..
00000050  0a:45:78:61:6d:70:6c:65:73:3a:0d:0a:20:3f:20:20  .Examples:.. ?  
00000060  20:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20                  
00000070  20:2d:20:4c:69:73:74:73:20:73:68:6f:72:74:20:64   - Lists short d
00000080  65:73:63:72:69:70:74:69:6f:6e:20:6f:66:20:61:6c  escription of al
00000090  6c:20:63:6f:6d:6d:61:6e:64:73:0d:0a:20:68:65:6c  l commands.. hel
000000a0  70:20:20:20:20:20:20:20:20:20:20:20:20:20:20:20  p               
000000b0  20:2d:20:4c:69:73:74:73:20:6c:6f:6e:67:20:64:65   - Lists long de
000000c0  73:63:72:69:70:74:69:6f:6e:20:6f:66:20:61:6c:6c  scription of all
000000d0  20:63:6f:6d:6d:61:6e:64:73:0d:0a:20:68:65:6c:70   commands.. help
000000e0  20:76:6c:61:6e:20:20:20:20:20:20:20:20:20:20:20   vlan           
000000f0  2d:20:4c:69:73:74:73:20:6f:6e:6c:79:20:63:6f:6d  - Lists only com
00000100  6d:61:6e:64:73:20:77:69:74:68:20:6b:65:79:77:6f  mands with keywo
00000110  72:64:20:76:6c:61:6e:0d:0a:20:68:65:6c:70:20:76  rd vlan.. help v
00000120  6c:61:6e:20:69:6e:74:65:72:66:61:63:65:20:2d:20  lan interface - 
00000130  4c:69:73:74:73:20:6f:6e:6c:79:20:63:6f:6d:6d:61  Lists only comma
00000140  6e:64:73:20:77:69:74:68:20:6b:65:79:77:6f:72:64  nds with keyword
00000150  20:76:6c:61:6e:20:61:6e:64:20:69:6e:74:65:72:66   vlan and interf
00000160  61:63:65:0d:0a:0d:0a:46:54:54:4f:2d:43:31:2d:41  ace....FTTO-C1-A
00000170  2d:42:44:5a:32:2d:6e:61:2d:31:33:2d:31:34:2d:43  -BDZ2-na-13-14-C
00000180  31:2d:31:30:36:2e:67:72:65:6e:6f:62:6c:65:2e:63  1-106.grenoble.c
00000190  6e:72:73:2e:66:72:23                             nrs.fr#

-> NET_SSH2_MSG_DISCONNECT (since last: 0.0002, network: 0.0001s)
00000000  00:00:00:0b:00:00:00:00:00:00:00:00              ............

Unable to open channel
```

**Comment by terrafrost** [comment]
```
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0003, network: 0.0001s)
00000000  00:00:00:2b:00:00:00:07:70:74:79:2d:72:65:71:01  ...+....pty-req.
00000010  00:00:00:05:76:74:31:30:30:00:00:00:50:00:00:00  ....vt100...P...
00000020  18:00:00:00:00:00:00:00:00:00:00:00:01:00        ..............

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0263, network: 0.0262s)
```
The server SHOULD be responding with NET_SSH2_MSG_CHANNEL_SUCCESS or NET_SSH2_MSG_CHANNEL_SUCCESS.

Quoting https://tools.ietf.org/html/rfc4254#section-5.4 :

```
   All channel-specific requests use the following format.

      byte      SSH_MSG_CHANNEL_REQUEST
      uint32    recipient channel
      string    request type in US-ASCII characters only
      boolean   want reply
      ....      type-specific data follows

   If 'want reply' is FALSE, no response will be sent to the request.
   Otherwise, the recipient responds with either
   SSH_MSG_CHANNEL_SUCCESS, SSH_MSG_CHANNEL_FAILURE, or request-specific
   continuation messages.  If the request is not recognized or is not
   supported for the channel, SSH_MSG_CHANNEL_FAILURE is returned.
```
"want reply", in this case, is 0x01, which is true.

Now the specs do say "_or request-specific continuation message_". I suppose just I could interpret the immediate sending of data as a "request-specific continuation message".

So based on your logs an exception _should_ be thrown. A "_Unable to request pseudo-terminal_" exception. But the exception you're saying is being thrown is a "_Unable to open channel_", which is just weird.

Regardless...  so you said it worked fine in OpenSSH. For good measure can you try it in PuTTY too? And if you can do that can you get me the PuTTY logs? You can get them by going to Session -> Logging -> Session logging and selecting "SSH packets".

If PuTTY is doing the same thing as OpenSSH I'll make it accept SSH_MSG_CHANNEL_DATA messages in response as well. If PuTTY is doing something to somehow avoid the error I'd like to know that too!

**Comment by dominiquefournier** [comment]
The switch works well with Putty and here is the log in attachment.
[putty.log](https://github.com/phpseclib/phpseclib/files/6195203/putty.log)
Good debug !

**Comment by terrafrost** [comment]
Does https://github.com/terrafrost/phpseclib/tree/nexans-3.0 fix the issue for you?

It's hard for me to verify the fix since I don't have a Nexans switch but I can verify that it doesn't break it on an SSH server that doesn't behave as Nexans does!

**Comment by dominiquefournier** [comment]
There is a new exception generated : 
```
PHP Fatal error:  Uncaught InvalidArgumentException: Bytes must be represented as an integer between 0 and 255, inclusive. in /home/fournier/Programmation/PHP/phpseclib/Original/vendor/phpseclib/phpseclib/phpseclib/Common/Functions/Strings.php:158
Stack trace:
#0 /home/fournier/Programmation/PHP/phpseclib/Original/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2777): phpseclib3\Common\Functions\Strings::packSSH2('CNsCsN4s', 98, 43, 'pty-req', true, 'vt100', 80, 24, 0, 0, '\x00')
#1 /home/fournier/Programmation/PHP/phpseclib/Original/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2910): phpseclib3\Net\SSH2->initShell()
#2 /home/fournier/Programmation/PHP/phpseclib/Original/test.php(13): phpseclib3\Net\SSH2->read('~#~', 2)
#3 {main}
  thrown in /home/fournier/Programmation/PHP/phpseclib/Original/vendor/phpseclib/phpseclib/phpseclib/Common/Functions/Strings.php on line 158
```
Sorry...

**Comment by terrafrost** [comment]
I just made a commit that should fix that.

Sorry about that.

It's failing in the 5.6 unit tests (which are also the most time consuming unit tests) but not the 7.0-8.0 unit tests. I think a lot of that is because GNU Parallels tends to [obscure errors](https://github.com/phpseclib/phpseclib/issues/1548#issuecomment-741494157). It's used because xdebug really slows things down and xdebug, in turn, is used to generate test coverage reports, which I don't really pay too much attention too (tbh I'm not sure 100% test coverage is ever going to be possible). If I remove xdebug the speedups GNU Parallels provide become less important.

**Comment by dominiquefournier** [comment]
No more uncatched exception but a different catched one 
[error.log](https://github.com/phpseclib/phpseclib/files/6222005/error.log)

**Comment by terrafrost** [comment]
Try https://github.com/terrafrost/phpseclib/tree/nexans-3.0 again.

Rather then add a third commit I squashed what would have been the three commits into one commit.

Thanks!

**Comment by dominiquefournier** [comment]
Genius ! It works ! Thanks a lot !! Well done to create the patch without access to the equipment !

**Comment by terrafrost** [comment]
These changes are in the 1.0 / 2.0 / 3.0 / master branches in the main repo!

I should probably update the behavior in a few other places as well:

- `exec()` when `enablePTY()` has been called
- `requestAgentForwarding()`
- `startSubsystem()`
- `SFTP::login()`

**Comment by dominiquefournier** [comment]
I don't know if the switches supports sftp and exec, but I can try tuesday.

**Comment by dominiquefournier** [comment]
Just test sftp and the switch don't supports it : 
```
$ sftp admin@192.168.255.165
admin@192.168.255.165's password: 
Received message too long 218776942
Ensure the remote shell produces no output for non-interactive sessions.
```
