### ISSUE TITLE
Issues with authenticating to a host?

### ISSUE THREAD

**Issue by ESPHayden** [phpseclib/phpseclib#1685]
```
[2021-08-02 11:49:33] local.ERROR: Invalid size {"exception":"[object] (RuntimeException(code: 0): Invalid size at /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3378)
[stacktrace]
#0 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3220): phpseclib3\\Net\\SSH2->read_remaining_bytes(724)
#1 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1470): phpseclib3\\Net\\SSH2->get_binary_packet()
#2 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1346): phpseclib3\\Net\\SSH2->key_exchange()
#3 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2085): phpseclib3\\Net\\SSH2->connect()
#4 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2070): phpseclib3\\Net\\SSH2->sublogin('user', Object(phpseclib3\\Crypt\\RSA\\PrivateKey))
#5 /var/www/html/src/Models/Host.php(162): phpseclib3\\Net\\SSH2->login('user', Object(phpseclib3\\Crypt\\RSA\\PrivateKey))
```

Can someone help me out here and tell me what I'm doing wrong?

I'm running the following code:

```php
$credential = $this->credentials;
$username = $credential->username;
try {
  $keyString = implode("\n", explode("\r\n", Crypt::decryptString($credential->secret)));
  $privateKey = PublicKeyLoader::load($keyString);
} catch (Exception $e) {
  throw new Exception('Failed to load private key for host.', 1);
}

if (!$ssh->login($username, $privateKey)) {
  throw new Exception('Failed to authenticate with host using provided credentials.', 2);
}
```

`$credential->secret` is an encrypted form of an RSA SSH key.

**Comment by terrafrost** [comment]
It looks like you're running 3.0.9 of phpseclib?

Can you post the output of `$ssh->getServerIdentification()`? Also, if you could provide the output of `$ssh->getServerAlgorithms()` and `$ssh->getAlgorithmsNegotiated()` that'd be cool (the latter two will be arrays).
