### ISSUE TITLE
Uncaught RuntimeException: Error reading from socket in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3390

### ISSUE THREAD

**Issue by kenITR** [phpseclib/phpseclib#1700]
Hi,
I am getting the above error when trying to submit an SFTP login with a user name and a PrivateKey object using phpseclib3

$this->key = PublicKeyLoader::loadPrivateKey(file_get_contents($dest));
$loginOK = $this->sftp->login($user, $this->key);

I can SFTP with the key text from the command line but not from phpseclib. 
It's unclear to me that I should be submitting a PrivateKey object at login or just the key text, but neither way is working for me. 
What am I missing?
Thanks.

**Comment by kenITR** [comment]
Hi,

I submitted both ways, a string and an object. I think you are seeing the log data for the string because it bombs on login and before the logs are retrieved.

It is failing on line 451 of SFTP.php

if (!parent::login(...func_get_args())) {

In:

public function login($username, ...$args)
    {
        if (!parent::login(...func_get_args())) {
            return false;
        }

        return $this->init_sftp_connection();
    }

Note: $username is not used. I've not seen "..." used in PHP.

I check the type and format as I go through. It

it's a Private Key and it's PKCS1.

If you give me a private email address I can share the key.

Ken

**Comment by terrafrost** [comment]
> I submitted both ways, a string and an object. I think you are seeing the log data for the string because it bombs on login and before the logs are retrieved.

I'm saying that because it's trying to do password auth (as opposed to publickey auth) here:

```
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0021, network: 0s)
00000000  00:00:00:04:68:63:69:74:00:00:00:0e:73:73:68:2d  ....hcit....ssh-
00000010  63:6f:6e:6e:65:63:74:69:6f:6e:00:00:00:08:70:61  connection....pa
00000020  73:73:77:6f:72:64:00:00:00:00:08:70:61:73:73:77  ssword.....passw
00000030  6f:72:64                                         ord
```

> Note: $username is not used. I've not seen "..." used in PHP.

`...` represents a [variable-length argument list](https://www.php.net/manual/en/functions.arguments.php#functions.variable-arg-list)

Anyway, my email is terrafrost@php.net. Thanks!

**Comment by kenITR** [comment]
Hi,
I know the key is right because I can use it on the command line:

> sftp -i /var/www/includes-hc/Keys/TellusGA.pem hcit@sftp-gateway.4tellus.com:/home/hcit/local/outbound/test/
Also, you commented that my code to use phpseclib was correct:

> // log into Tellus outbound files
> $sftp = new SFTPTransfer;
> $dest = "sftp-gateway.4tellus.com";
> $sftp->setKey(INCLUDES."Keys/TellusGA.pem");
> define('NET_SSH2_LOGGING', 2);
>
> $sftp->open($dest, 'hcit', null);

So why does phpseclib code bomb on line 451 of SFTP

> public function login($username, ...$args)
>     {
>         if (!parent::login(...func_get_args())) {
>             return false;
>         }
>
>         return $this->init_sftp_connection();
>     }

I'm using php7.3.

Thanks,

Ken

**Comment by terrafrost** [comment]
The title for this issue references SSH2.php:3390. In 3.0.10 of phpseclib that corresponds to this:

https://github.com/phpseclib/phpseclib/blob/418035c404833187f7474c71e0ba06c167b0bcf0/phpseclib/Net/SSH2.php#L3386-L3394
That's in the `read_remaining_bytes` method. So try this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
            $temp = stream_get_contents($this->fsock, $remaining_length);
            if ($temp === false || feof($this->fsock)) {
#
#-----[ AFTER, ADD ]------------------------------------
#
if ($temp === false) echo "temp === false\n";
if (feof($this->fsock)) echo "feof\n";
var_dump(stream_get_meta_data($this->fsock));
```
This will not fix the issue but it'll hopefully give me a better idea of what's going on.

**Comment by chrisjove** [comment]
I'm receiving this error also. It looks like the code has changed since `Dec 9, 2021`.  The `stream_get_contents` line has changed and `if ($temp === false || feof($this->fsock)) {` is no longer present. My error message is:

```php
PHP Fatal error:  Uncaught RuntimeException: Error reading from socket in /var/www/cron/phpsec/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1408
Stack trace:
#0 /var/www/cron/phpsec/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2220): phpseclib3\Net\SSH2->connect()
#1 /var/www/cron/phpsec/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2199): phpseclib3\Net\SSH2->sublogin('user')
#2 /var/www/cron/new_inspec.php(9): phpseclib3\Net\SSH2->login('user', 'password')
#3 {main}
  thrown in /var/www/cron/phpsec/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1408
``` 

I'm not using the keyloader, ssh2 to SFTP to a machine.

**Comment by terrafrost** [comment]
@chrisjove - Based on the line #, you're getting that error whilst phpseclib is trying to get the server identification string. This kinda makes me wonder what it is for you.

Are you able to connect with PuTTY? If so then if you could get me the PuTTY logs that'd be great. You can enable logging in PuTTY by going to putty.exe, selecting the Logging category and checking "SSH packets".  You'll also want to set the Log file name to whatever.

If you're using password authentication feel free to login with the wrong password - all I want to see is the server identification string and that's it.

Alternatively, if you could give me the domain name or IP address of the server (if it's publicly accessible) I could get that inf myself. You wouldn't need to create an account for me or anything. If you're willing to share this but don't want to do so publicly you can email that info to me at terrafrost@php.net.

Thanks!

**Comment by terrafrost** [comment]
@chrisjove - I just made a commit that _might_ fix the issue for you, hard to say (whether or not it'd make a difference depends on the length of your server identifications strings). Let me know if it helps...  or if it doesn't.

Thanks!
