### ISSUE TITLE
Connection closed prematurely

### ISSUE THREAD

**Issue by mstaudinger** [phpseclib/phpseclib#1715]
I'm evaluating using phpseclib to gather running configuration from Cisco routers.  The account used for this purpose automatically runs 'show run' upon login, using the 'autocommand' setting.  As such, there is no opportunity to set a terminal length of 0, and the output is therefore interrupted by '--More--" prompts every 24 lines.  Sending a 'space' will allow the next set of lines to be read.

All this works a treat until the last set.  Sometimes it works, other times (more often) I get this.

PHP Fatal error:  Uncaught phpseclib3\Exception\ConnectionClosedException: Connection closed prematurely in ./include/phpseclib/phpseclib/Net/SSH2.php:4044
Stack trace:
#0 ./include/phpseclib/phpseclib/Net/SSH2.php(4013): phpseclib3\Net\SSH2->send_binary_packet('a\x00\x00\x00\x03')
#1 ./include/phpseclib/phpseclib/Net/SSH2.php(3018): phpseclib3\Net\SSH2->get_channel_packet(2)
#2 ./test-backup.php(168): phpseclib3\Net\SSH2->read('/--More--|end$/', 2)
#3 {main}
  thrown in ./include/phpseclib/phpseclib/Net/SSH2.php on line 4044

As soon as the 'show run' command is done sending output it logs the user out, and the SSH connection is destroyed, so it seems that I'm reading too late.  Are there any alternate methods for reading that would prevent this?

**Comment by terrafrost** [comment]
Can you post the code you're using to do this? I don't need to see the part where you login but anything and everything after that, so long as it shows the phpseclib calls.

Also, can you post the log files? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `$ssh->getLog()` in a try / catch block or something, after the error. If the output is too large for a post you can post it on pastebin.com and then post a link here. Alternatively, you could email me the files. terrafrost@php.net.

**Comment by mstaudinger** [comment]
Thanks!

Here's the sample code block, which immediately follows the login, and includes the new bit to catch the exception.  I'll follow up here or by email with the output of $ssh->getLog()

      $ssh->enablePTY();
      $auto = $ssh->read( '--More--' );
      // convert output into line array as we go along
      $running = array();
      if ( strpos( $auto, '--More--' ) !== FALSE ) {
        $running = read_lbl ( $auto );
        while ( strpos( $auto, '--More' ) !== FALSE && array_search(  'end', $running ) === FALSE ) {
          if ( $ssh->isConnected() ) {
            $ssh->write(' ');
            $ssh->setTimeout(1);
            if ( $ssh->isConnected() ) {
              try {
                $auto = $ssh->read( "/--More--|end$/", SSH2::READ_REGEX );
              } catch ( Exception $ex ) {
                echo $ex->getMessage();
                echo $ssh->getLog();
                exit(1);
              }
              $running = array_merge( $running, read_lbl ( $auto ) );
            }
          }
        }
      } else { // Connect and run the commands directly
        $ssh->write( "terminal length 0\n" );
        check( $ssh->isConnected(), __FILE__, __LINE__, $message, FALSE, FALSE );
        $ssh->read( "\n" );
        $ssh->write( "show running-config\n" );
        $running = read_lbl( $ssh->read('') );
      }

**Comment by terrafrost** [comment]
idk what the `read_lbl` function does but idk that it's that important.

From the log files you emailed me:

```
<- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.1018, network: 0.0001s)
00000000  00:00:00:02:00:00:00:0b:65:78:69:74:2d:73:74:61  ........exit-sta
00000010  74:75:73:00:00:00:00:00                          tus.....

<- NET_SSH2_MSG_CHANNEL_EOF (since last: 0.0001, network: 0s)
00000000  00:00:00:02                                      ....

<- NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0002, network: 0s)
00000000  00:00:00:02                                      ....
```
The server _is_ closing the connection. If you were connecting to an OpenSSH server I'd suggest trying to do `sudo /usr/sbin/sshd -ddd -p2222` to see what the server logs are saying but I don't imagine Cisco IOS provides anything like that.

I mean, I don't think it ought to be throwing the exception. You might have better luck if you do `$ssh->read( "/--More--|end\r\n$/", SSH2::READ_REGEX );` instead 'cause the last packet doesn't end with `end` - it ends with `end\r\n`.

**Comment by mstaudinger** [comment]
Well, that's a great suggestion, and in fact it does look promising for my use case - I haven't encountered the exception after modifying that read_regex in repeated trials across multiple devices.  More testing awaits.

Just to gather additional data, I changed the last read to $ssh->read(''); and got the same exception, so it's not specific to using a read string, READ_REGEX, or any particular regex.

A more general summary of the problem seems to be: a "Connection closed prematurely " exception is thrown if we receive CHANNEL_EOF during a read where the read string has not matched and the timeout has not yet expired.

Is there a more general way to prevent this?  In my case I know my text will end with "end\r\n\r\n", but that's particular to this one use case.

Is there a way to match an EOF during the read() via string or regex?  If not, perhaps CHANNEL_EOF during a read, instead of throwing this exception, could result in the output of the stream read so far as if the timeout had expired, or the read string had been matched?

**Comment by terrafrost** [comment]
> Just to gather additional data, I changed the last read to $ssh->read(''); and got the same exception, so it's not specific to using a read string, READ_REGEX, or any particular regex.

When you pass the empty string to `$ssh->read()` it reads until there's a timeout. By default phpseclib times out after 10s but this can be adjusted with [`$ssh->setTimeout()`](https://phpseclib.com/docs/commands#settimeout). In your case the server is closing the connection, itself before phpseclib's timeout can take effect.

> Is there a way to match an EOF during the read() via string or regex? If not, perhaps CHANNEL_EOF during a read, instead of throwing this exception, could result in the output of the stream read so far as if the timeout had expired, or the read string had been matched?

Yah - I'll look into that!

**Comment by terrafrost** [comment]
So I was thinking about it and...

https://github.com/phpseclib/phpseclib/blob/779e11e4963c52bc9fa690c370ce7f528053b99a/phpseclib/Net/SSH2.php#L4040-L4045

You're getting the exception from that line. So either `$this->fsock` is no longer a resource or `feof($this->fsock)` is returning true. Either way I'm not sure that there's anything I can do.

Why is `send_binary_packet` being called? Because in `get_binary_packet` an SSH_MSG_CHANNEL_CLOSE was received:

https://github.com/phpseclib/phpseclib/blob/779e11e4963c52bc9fa690c370ce7f528053b99a/phpseclib/Net/SSH2.php#L4006-L4019

It's doing that because that's what the SSH specs ([RFC4254: SSH Connection Protocol § 5.3.  Closing a Channel](https://datatracker.ietf.org/doc/html/rfc4254#section-5.3)) say to do:

```
   When either party wishes to terminate the channel, it sends
   SSH_MSG_CHANNEL_CLOSE.  Upon receiving this message, a party MUST
   send back an SSH_MSG_CHANNEL_CLOSE unless it has already sent this
   message for the channel.  The channel is considered closed for a
   party when it has both sent and received SSH_MSG_CHANNEL_CLOSE, and
   the party may then reuse the channel number.
```
So I believe phpseclib is correct to be throwing the exception.

That said, I guess you could try this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
            $response = $this->get_channel_packet($channel);
#
#-----[ REPLACE WITH ]----------------------------------
#
            try {
                $response = $this->get_channel_packet($channel);
            } catch (ConnectionClosedException $e) {
                return Strings::shift($this->interactiveBuffer, strlen($this->interactiveBuffer));
            }
```
I'm not gonna incorporate that into phpseclib but if it works for you then that's cool!

**Comment by terrafrost** [comment]
Closing due to inactivity.
