### ISSUE TITLE
Can someone tell me why on Raspberry Pi this lib is not working

### ISSUE THREAD

**Issue by bluecraank** [phpseclib/phpseclib#1820]
Error: Unable to verify that point exists on curve in [phpseclib/Crypt/EC/Formats/Keys/Common.php:289]

Trying to connect to aruba switch (RSA Public Key)

Same Code on Debian Server is working.

Installed packages on both:
php8.1-gmp
php8.1-bcmath

**Comment by terrafrost** [comment]
I had issues getting this to work on a Raspberry Pi until I made this change:

https://github.com/phpseclib/phpseclib/commit/0b3cc980840a79edc979fba7a0e4915fed2210e0

#1807 got me to try it out on a Raspberry Pi but the original bug reporter said that the code change I had didn't work for him. All I can say is that it worked for me on my Raspberry Pi 4 8GB. Maybe it'll work for you?

Also, what are you trying to do on the Raspberry Pi? SSH into another machine or something else?

**Comment by bluecraank** [comment]
`$ssh->login($this->config['default_user'], $passphrase)`

getLog() output:

<pre><-
00000000  53:53:48:2d:32:2e:30:2d:4d:6f:63:61:6e:61:20:53  SSH-2.0-Mocana S
00000010  53:48:20:36:2e:33:0d:0a                          SH 6.3..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:33:2e:30:20:28:6c:69:62:73:6f:64:69:75:6d  b_3.0 (libsodium
00000020  2c:20:6f:70:65:6e:73:73:6c:29:0d:0a              , openssl)..

-> NET_SSH2_MSG_KEXINIT (since last: 0.0219, network: 0.0001s)
00000000  2e:34:7c:ce:be:9c:40:3e:54:db:45:83:d4:60:55:6a  .4|...@>T.E..`Uj
00000010  00:00:01:7c:63:75:72:76:65:32:35:35:31:39:2d:73  ...|curve25519-s
00000020  68:61:32:35:36:2c:63:75:72:76:65:32:35:35:31:39  ha256,curve25519
00000030  2d:73:68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f  -sha256@libssh.o
00000040  72:67:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73  rg,ecdh-sha2-nis
00000050  74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d  tp256,ecdh-sha2-
00000060  6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73:68  nistp384,ecdh-sh
00000070  61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66  a2-nistp521,diff
00000080  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000090  2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35:36  -exchange-sha256
000000a0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000b0  67:72:6f:75:70:2d:65:78:63:68:61:6e:67:65:2d:73  group-exchange-s
000000c0  68:61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ha1,diffie-hellm
000000d0  61:6e:2d:67:72:6f:75:70:31:34:2d:73:68:61:32:35  an-group14-sha25
000000e0  36:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e  6,diffie-hellman
000000f0  2d:67:72:6f:75:70:31:34:2d:73:68:61:31:2c:64:69  -group14-sha1,di
00000100  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000110  75:70:31:35:2d:73:68:61:35:31:32:2c:64:69:66:66  up15-sha512,diff
00000120  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000130  31:36:2d:73:68:61:35:31:32:2c:64:69:66:66:69:65  16-sha512,diffie
00000140  2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:37  -hellman-group17
00000150  2d:73:68:61:35:31:32:2c:64:69:66:66:69:65:2d:68  -sha512,diffie-h
00000160  65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:38:2d:73  ellman-group18-s
00000170  68:61:35:31:32:2c:64:69:66:66:69:65:2d:68:65:6c  ha512,diffie-hel
00000180  6c:6d:61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31  lman-group1-sha1
00000190  00:00:00:71:73:73:68:2d:65:64:32:35:35:31:39:2c  ...qssh-ed25519,
000001a0  65:63:64:73:61:2d:73:68:61:32:2d:6e:69:73:74:70  ecdsa-sha2-nistp
000001b0  32:35:36:2c:65:63:64:73:61:2d:73:68:61:32:2d:6e  256,ecdsa-sha2-n
000001c0  69:73:74:70:33:38:34:2c:65:63:64:73:61:2d:73:68  istp384,ecdsa-sh
000001d0  61:32:2d:6e:69:73:74:70:35:32:31:2c:72:73:61:2d  a2-nistp521,rsa-
000001e0  73:68:61:32:2d:32:35:36:2c:72:73:61:2d:73:68:61  sha2-256,rsa-sha
000001f0  32:2d:35:31:32:2c:73:73:68:2d:72:73:61:2c:73:73  2-512,ssh-rsa,ss
00000200  68:2d:64:73:73:00:00:01:01:61:65:73:31:32:38:2d  h-dss....aes128-
00000210  67:63:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  gcm@openssh.com,
00000220  61:65:73:32:35:36:2d:67:63:6d:40:6f:70:65:6e:73  aes256-gcm@opens
00000230  73:68:2e:63:6f:6d:2c:61:65:73:31:32:38:2d:63:74  sh.com,aes128-ct
00000240  72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73  r,aes192-ctr,aes
00000250  32:35:36:2d:63:74:72:2c:61:65:73:31:32:38:2d:63  256-ctr,aes128-c
00000260  62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c:61:65  bc,aes192-cbc,ae
00000270  73:32:35:36:2d:63:62:63:2c:62:6c:6f:77:66:69:73  s256-cbc,blowfis
00000280  68:2d:63:74:72:2c:62:6c:6f:77:66:69:73:68:2d:63  h-ctr,blowfish-c
00000290  62:63:2c:33:64:65:73:2d:63:74:72:2c:33:64:65:73  bc,3des-ctr,3des
000002a0  2d:63:62:63:2c:74:77:6f:66:69:73:68:31:32:38:2d  -cbc,twofish128-
000002b0  63:74:72:2c:74:77:6f:66:69:73:68:31:39:32:2d:63  ctr,twofish192-c
000002c0  74:72:2c:74:77:6f:66:69:73:68:32:35:36:2d:63:74  tr,twofish256-ct
000002d0  72:2c:74:77:6f:66:69:73:68:31:32:38:2d:63:62:63  r,twofish128-cbc
000002e0  2c:74:77:6f:66:69:73:68:31:39:32:2d:63:62:63:2c  ,twofish192-cbc,
000002f0  74:77:6f:66:69:73:68:32:35:36:2d:63:62:63:2c:74  twofish256-cbc,t
00000300  77:6f:66:69:73:68:2d:63:62:63:00:00:01:01:61:65  wofish-cbc....ae
00000310  73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73:73:68  s128-gcm@openssh
00000320  2e:63:6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d:40  .com,aes256-gcm@
00000330  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73:31  openssh.com,aes1
00000340  32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74  28-ctr,aes192-ct
00000350  72:2c:61:65:73:32:35:36:2d:63:74:72:2c:61:65:73  r,aes256-ctr,aes
00000360  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
00000370  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:62:6c  bc,aes256-cbc,bl
00000380  6f:77:66:69:73:68:2d:63:74:72:2c:62:6c:6f:77:66  owfish-ctr,blowf
00000390  69:73:68:2d:63:62:63:2c:33:64:65:73:2d:63:74:72  ish-cbc,3des-ctr
000003a0  2c:33:64:65:73:2d:63:62:63:2c:74:77:6f:66:69:73  ,3des-cbc,twofis
000003b0  68:31:32:38:2d:63:74:72:2c:74:77:6f:66:69:73:68  h128-ctr,twofish
000003c0  31:39:32:2d:63:74:72:2c:74:77:6f:66:69:73:68:32  192-ctr,twofish2
000003d0  35:36:2d:63:74:72:2c:74:77:6f:66:69:73:68:31:32  56-ctr,twofish12
000003e0  38:2d:63:62:63:2c:74:77:6f:66:69:73:68:31:39:32  8-cbc,twofish192
000003f0  2d:63:62:63:2c:74:77:6f:66:69:73:68:32:35:36:2d  -cbc,twofish256-
00000400  63:62:63:2c:74:77:6f:66:69:73:68:2d:63:62:63:00  cbc,twofish-cbc.
00000410  00:00:f7:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  ...hmac-sha2-256
00000420  2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  -etm@openssh.com
00000430  2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2d:65  ,hmac-sha2-512-e
00000440  74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75  tm@openssh.com,u
00000450  6d:61:63:2d:36:34:2d:65:74:6d:40:6f:70:65:6e:73  mac-64-etm@opens
00000460  73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:2d  sh.com,umac-128-
00000470  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000480  68:6d:61:63:2d:73:68:61:31:2d:65:74:6d:40:6f:70  hmac-sha1-etm@op
00000490  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
000004a0  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
000004b0  32:2d:35:31:32:2c:75:6d:61:63:2d:36:34:40:6f:70  2-512,umac-64@op
000004c0  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31  enssh.com,umac-1
000004d0  32:38:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68  28@openssh.com,h
000004e0  6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63  mac-sha1-96,hmac
000004f0  2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39  -sha1,hmac-md5-9
00000500  36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:f7:68:6d  6,hmac-md5....hm
00000510  61:63:2d:73:68:61:32:2d:32:35:36:2d:65:74:6d:40  ac-sha2-256-etm@
00000520  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
00000530  2d:73:68:61:32:2d:35:31:32:2d:65:74:6d:40:6f:70  -sha2-512-etm@op
00000540  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:36  enssh.com,umac-6
00000550  34:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f  4-etm@openssh.co
00000560  6d:2c:75:6d:61:63:2d:31:32:38:2d:65:74:6d:40:6f  m,umac-128-etm@o
00000570  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
00000580  73:68:61:31:2d:65:74:6d:40:6f:70:65:6e:73:73:68  sha1-etm@openssh
00000590  2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32  .com,hmac-sha2-2
000005a0  35:36:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32  56,hmac-sha2-512
000005b0  2c:75:6d:61:63:2d:36:34:40:6f:70:65:6e:73:73:68  ,umac-64@openssh
000005c0  2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:40:6f:70  .com,umac-128@op
000005d0  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
000005e0  68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68:61:31  ha1-96,hmac-sha1
000005f0  2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d:61  ,hmac-md5-96,hma
00000600  63:2d:6d:64:35:00:00:00:1a:6e:6f:6e:65:2c:7a:6c  c-md5....none,zl
00000610  69:62:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:7a  ib@openssh.com,z
00000620  6c:69:62:00:00:00:1a:6e:6f:6e:65:2c:7a:6c:69:62  lib....none,zlib
00000630  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:7a:6c:69  @openssh.com,zli
00000640  62:00:00:00:00:00:00:00:00:00:00:00:00:00        b.............

<- NET_SSH2_MSG_KEXINIT (since last: 0.0074, network: 0.0073s)
00000000  c6:91:03:42:1a:c3:84:8d:30:44:58:2e:9d:d5:86:5f  ...B....0DX...._
00000010  00:00:00:79:65:63:64:68:2d:73:68:61:32:2d:6e:69  ...yecdh-sha2-ni
00000020  73:74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32  stp256,ecdh-sha2
00000030  2d:6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73  -nistp384,ecdh-s
00000040  68:61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66  ha2-nistp521,dif
00000050  66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75  fie-hellman-grou
00000060  70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35  p-exchange-sha25
00000070  36:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e  6,diffie-hellman
00000080  2d:67:72:6f:75:70:31:34:2d:73:68:61:31:00:00:00  -group14-sha1...
00000090  21:72:73:61:2d:73:68:61:32:2d:35:31:32:2c:72:73  !rsa-sha2-512,rs
000000a0  61:2d:73:68:61:32:2d:32:35:36:2c:73:73:68:2d:72  a-sha2-256,ssh-r
000000b0  73:61:00:00:00:66:61:65:73:32:35:36:2d:63:74:72  sa...faes256-ctr
000000c0  2c:61:65:73:32:35:36:2d:63:62:63:2c:72:69:6a:6e  ,aes256-cbc,rijn
000000d0  64:61:65:6c:2d:63:62:63:40:6c:79:73:61:74:6f:72  dael-cbc@lysator
000000e0  2e:6c:69:75:2e:73:65:2c:61:65:73:31:39:32:2d:63  .liu.se,aes192-c
000000f0  74:72:2c:61:65:73:31:39:32:2d:63:62:63:2c:61:65  tr,aes192-cbc,ae
00000100  73:31:32:38:2d:63:74:72:2c:61:65:73:31:32:38:2d  s128-ctr,aes128-
00000110  63:62:63:2c:33:64:65:73:2d:63:62:63:00:00:00:66  cbc,3des-cbc...f
00000120  61:65:73:32:35:36:2d:63:74:72:2c:61:65:73:32:35  aes256-ctr,aes25
00000130  36:2d:63:62:63:2c:72:69:6a:6e:64:61:65:6c:2d:63  6-cbc,rijndael-c
00000140  62:63:40:6c:79:73:61:74:6f:72:2e:6c:69:75:2e:73  bc@lysator.liu.s
00000150  65:2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73  e,aes192-ctr,aes
00000160  31:39:32:2d:63:62:63:2c:61:65:73:31:32:38:2d:63  192-cbc,aes128-c
00000170  74:72:2c:61:65:73:31:32:38:2d:63:62:63:2c:33:64  tr,aes128-cbc,3d
00000180  65:73:2d:63:62:63:00:00:00:39:68:6d:61:63:2d:73  es-cbc...9hmac-s
00000190  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
000001a0  31:2d:39:36:2c:68:6d:61:63:2d:6d:64:35:2c:68:6d  1-96,hmac-md5,hm
000001b0  61:63:2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35  ac-sha1,hmac-md5
000001c0  2d:39:36:00:00:00:39:68:6d:61:63:2d:73:68:61:32  -96...9hmac-sha2
000001d0  2d:32:35:36:2c:68:6d:61:63:2d:73:68:61:31:2d:39  -256,hmac-sha1-9
000001e0  36:2c:68:6d:61:63:2d:6d:64:35:2c:68:6d:61:63:2d  6,hmac-md5,hmac-
000001f0  73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36  sha1,hmac-md5-96
00000200  00:00:00:04:6e:6f:6e:65:00:00:00:04:6e:6f:6e:65  ....none....none
00000210  00:00:00:00:00:00:00:00:00:00:00:00:00           .............

</pre>

Than, this error appears: 

`Can't connect to host RuntimeException: Unable to verify that point exists on curve in /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/Common.php:330
Stack trace:
#0 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/PKCS8.php(117): phpseclib3\Crypt\EC\Formats\Keys\PKCS8::extractPoint()
#1 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php(263): phpseclib3\Crypt\EC\Formats\Keys\PKCS8::load()
#2 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/PrivateKey.php(245): phpseclib3\Crypt\Common\AsymmetricKey::loadFormat()
#3 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1770): phpseclib3\Crypt\EC\PrivateKey->getPublicKey()
#4 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1516): phpseclib3\Net\SSH2->key_exchange()
#5 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2271): phpseclib3\Net\SSH2->connect()
#6 /var/www/html/cesma/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2249): phpseclib3\Net\SSH2->sublogin()
#7 /var/www/html/cesma/classes/SSH.php(144): phpseclib3\Net\SSH2->login()
#8 /var/www/html/cesma/classes/SwitchController.php(156): classes\SSH->executeCommand()
#9 /var/www/html/cesma/classes/Api.php(7): classes\SwitchController->execute()
#10 /var/www/html/cesma/routes.php(60): classes\Api::doExecution()
#11 [internal function]: {closure}()
#12 /var/www/html/cesma/vendor/bramus/router/src/Bramus/Router/Router.php(458): call_user_func_array()
#13 /var/www/html/cesma/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\Router\Router->invoke()
#14 /var/www/html/cesma/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\Router\Router->handle()
#15 /var/www/html/cesma/routes.php(64): Bramus\Router\Router->run()
#16 /var/www/html/cesma/public/index.php(34): require('...')
#17 {main}`

I change code to commit https://github.com/phpseclib/phpseclib/commit/0b3cc980840a79edc979fba7a0e4915fed2210e0
but unfortunately its not the fix.

**Comment by terrafrost** [comment]
Well I'm only able to reproduce the issue when I (1) undo https://github.com/phpseclib/phpseclib/commit/0b3cc980840a79edc979fba7a0e4915fed2210e0 and (2) when I make my cipher suite match yours by doing `$ssh->setPreferredAlgorithms(['kex' => ['ecdh-sha2-nistp256']]);` immediately after the constructor.

You say you have php8.1-gmp installed but phpseclib doesn't think so. You can tell from this:

```
->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:33:2e:30:20:28:6c:69:62:73:6f:64:69:75:6d  b_3.0 (libsodium
00000020  2c:20:6f:70:65:6e:73:73:6c:29:0d:0a              , openssl)..
```
If php8.1-gmp was installed it'd say so there. Here's the code that makes it do that:

https://github.com/phpseclib/phpseclib/blob/0a699725711b450aae358d29e8b045d1d0414069/phpseclib/Net/SSH2.php#L1547-L1555

So `extension_loaded('gmp')` isn't returning true.

I'd double check your copy of PHP32.php. I suppose you could post it here or on pastebin.com and post the pastebin.com link here.

Alternatively, you could tarball it up and email it to me at terrafrost@php.net. idk if giving me SSH access to the server that demonstrates the problem is realistic.

**Comment by terrafrost** [comment]
Closing due to inactivity.

I've tested this pretty thoroughly on Raspberry Pi's, on multiple different PHP versions, as part of my work on this:

https://github.com/phpseclib/phpseclib/commit/ccbb116db3dfd2eb7fad22777fc82f5659831706

(I've only ever been able to reproduce that issue on a Raspberry Pi and I wanted to impose some restrictions on when that inelegant workaround would be used, hence my putting forward the effort to try phpseclib on so many different PHP versions on Raspberry Pi)

In no case was phpseclib unable to run on a Raspberry Pi for me.
