### ISSUE TITLE
Connection ok but always Fatal on strlen() expects parameter 1 to be string

### ISSUE THREAD

**Issue by DevPerlesAndCo** [phpseclib/phpseclib#1825]
Hi, 

I use the version 3.

I use it simple with :
`$sftp = new SFTP($ftp_server);` and `$connect = $sftp->login($ftp_user_name, $ftp_mdp) or die("Echec");`
Everything is ok here.
`$sftp->isConnected())` and `$sftp->isAuthenticated()` send true both.

But when I use
`$sftp->pwd()` or `$sftp->mkdir('sftp')` or `$sftp->chdir('sftp')` or `$sftp->put($key, file_get_contents($filename))`
I have always same issue :
PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, bool given in /lib/phpseclib/phpseclib/Net/SSH2.php:4039
Stack trace:
#0 /lib/phpseclib/phpseclib/Net/SSH2.php(4039): strlen(false)
#1 /lib/phpseclib/phpseclib/Net/SFTP.php(2873): phpseclib3\Net\SSH2->send_channel_packet(256, false)
#2 /lib/phpseclib/phpseclib/Net/SFTP.php(405): phpseclib3\Net\SFTP->send_sftp_packet(1, '\x00\x00\x00\x03')
#3 /lib/phpseclib/phpseclib/Net/SFTP.php(431): phpseclib3\Net\SFTP->partial_init_sftp_connection()
#4 /lib/phpseclib/phpseclib/Net/SFTP.php(331): phpseclib3\Net\SFTP->init_sftp_connection()
#5 /lib/phpseclib/phpseclib/Net/SFTP.php(713): phpseclib3\Net\SFTP->precheck()
#6 /home/..../archivesPC.php(38): phpseclib3\Net\SFTP->chdir('sftp')
#7 {main}
  thrown in /lib/phpseclib/phpseclib/Net/SSH2.php on line 4039

**Comment by terrafrost** [comment]
Which version of 3.0 are you using?

Line 2873 in SFTP.php on v3.0.14 is `case NET_SFTP_TYPE_CHAR_DEVICE:`.

https://github.com/phpseclib/phpseclib/blob/3.0.14/phpseclib/Net/SFTP.php#L2873

Your stack trace shows `send_channel_packet` being called from `send_sftp_packet`. Here are the first few lines of `send_sftp_packet` (which starts on line 3272, which is no where close to line 2873).

```php
    private function send_sftp_packet($type, $data, $request_id = 1)
    {
        // in SSH2.php the timeout is cumulative per function call. eg. exec() will
        // timeout after 10s. but for SFTP.php it's cumulative per packet
        $this->curTimeout = $this->timeout;

        $packet = $this->use_request_id ?
            pack('NCNa*', strlen($data) + 5, $type, $request_id, $data) :
            pack('NCa*', strlen($data) + 1, $type, $data);

        $start = microtime(true);
        $this->send_channel_packet(self::CHANNEL, $packet);
```
So `$packet` can either be `pack('NCNa*', strlen($data) + 5, $type, $request_id, $data)` or `pack('NCa*', strlen($data) + 1, $type, $data)` depending on `$this->use_request_id`. We can deduce the value of that variable from the fact that it's being called from partial_init_sftp_connection() but let's not, for the time being.

If `$this->use_request_id` is true then `$packet` would be as follows:

```php
pack(
    'NCNa*',
    9, // $data is '\x00\x00\x00\x03' in the stacktrace and this is strlen($data) + 5
    1, // $type is 1 in the stacktrace
    1, // $request_id is 1 if it's not passed as a third parameter to send_sftp_packet, which it isn't, in the stacktrace
    "\x00\x00\x00\x03" // value of $data in the stacktrace
);
```
It looks the same if `$this->use_request_id` is false except that it's just `9, 1, $data` instead of `9, 1, 1, $data`.

Looking it up I guess `pack()` _can_ return false but I know of no reason why it would given what's being passed to it.

Can you try the `pack()` that I just posted on your system? If that returns false then I guess you could post your phpinfo()` output? But, really, in that scenario, making a bug report at https://github.com/php/php-src/issues

**Comment by terrafrost** [comment]
Closing due to inactivity
