### ISSUE TITLE
How to handle this error to log it in php?

### ISSUE THREAD

**Issue by mikmikmik** [phpseclib/phpseclib#1938]
I had this error happened once:
```
PHP Fatal error:  Uncaught RuntimeException: Error reading from socket in /home/.../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1382
Stack trace:
#0 /home/.../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2205): phpseclib3\Net\SSH2->connect()
#1 /home/.../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2184): phpseclib3\Net\SSH2->sublogin('PLAIDS')
#2 /home/.../someplugin.php(423): phpseclib3\Net\SSH2->login('login', 'pass')
#3 /home/.../class-api.php(161): MyClass->send_file_to_ftp('filename', '<?xml version="...')
```
This the function:
```
            private function send_file_to_ftp($filename, $xml):bool
            {

                $sftp = new \phpseclib3\Net\SFTP($this->sftp_url, 22);
                if (!$sftp->login($this->sftp_user, $this->sftp_pass)) {
                    exit('Login Failed');
                }
                $sftp->chdir('FOLDER');
                $status = $sftp->put($filename, $xml);
                return $status;

            }
```

**Comment by mikmikmik** [comment]
Or should I use a try catch for every step?

**Comment by terrafrost** [comment]
Yah - as it's throwing an exception you'd need to catch it.

That said, if you want to understand why it's not connecting, enabling logging by doing `define('NET_SSH2_LOGGING', 2);` at the top and `echo $ssh->getLog();` after the error would be helpful. Then post the output here and I can take a look.
