### ISSUE TITLE
Close channel before trying to open again Exception is raised upon folder creation

### ISSUE THREAD

**Issue by Naoray** [phpseclib/phpseclib#1961]
I am using the `flysystem-sftp-v3` in a Laravel app which uploads files to a SFTP server around 500times a month. Occasionally I get the error `Please close the channel (256) before trying to open it again` from `SSH2::openChannel()` when trying to run `Storage::disk(’sftp’)->makeDirectory(‘folder_name’)`.

I tried to check the code to understand what the error means and how to avoid it, but I wasn’t able to figure it out myself. Can someone explain to me or point me in the right direction on when this happens and why?

```
    RuntimeException Please close the channel (256) before trying to open it again 
    vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2885 phpseclib3\Net\SSH2::openChannel
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:550 phpseclib3\Net\SFTP::partial_init_sftp_connection
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:624 phpseclib3\Net\SFTP::init_sftp_connection
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:536 phpseclib3\Net\SFTP::precheck
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2931 phpseclib3\Net\SFTP::get_xstat_cache_prop
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2902 phpseclib3\Net\SFTP::get_stat_cache_prop
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2668 phpseclib3\Net\SFTP::is_dir
    vendor/league/flysystem-sftp-v3/SftpAdapter.php:112 League\Flysystem\PhpseclibV3\SftpAdapter::makeDirectory
    vendor/league/flysystem-sftp-v3/SftpAdapter.php:194 League\Flysystem\PhpseclibV3\SftpAdapter::createDirectory
    vendor/league/flysystem/src/Filesystem.php:95 League\Flysystem\Filesystem::createDirectory
    vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:876 Illuminate\Filesystem\FilesystemAdapter::makeDirectory
    app/Services/Kontor/Jobs/UploadReleaseFolder.php:69 App\Jobs\UploadReleaseFolder::handle
```

**Comment by terrafrost** [comment]
I can get a similar error if I try to do certain operations more than once. eg.

```php
$sftp->openShell();
$sftp->openShell();
```
I mean, I should prob update it to work more like the DocBlock comments describe:

```php
     * Creates an interactive shell
     *
     * Returns bool(true) if the shell was opened.
     * Returns bool(false) if the shell was already open.
```
Anyway, it almost feels like what's going is that the connection is getting interrupted and then phpseclib is trying to reconnect.

I think https://github.com/phpseclib/phpseclib/commit/8ecd156ce1e932f38333571e530885ac4df52bc6 should do the trick for you.

Thanks!

**Comment by Naoray** [comment]
Thanks @terrafrost. Will upgrade and report back if the error happens again!

**Comment by Naoray** [comment]
@terrafrost, the issue still persists :-/. Any other ideas?

**Comment by terrafrost** [comment]
So I was able to test my theory and had to make one more tweak for it to work:

https://github.com/phpseclib/phpseclib/commit/404f86fb61fed2fc174ab7844252d2750c268f6e

That said, if my theory were true you'd also need to do `$sftp->ping()` as well. So like let's say you had this code:

```php
$ssh = new SFTP('localhost', 22);
$ssh->login('user', 'pass');

echo $ssh->pwd() . "\n";
sleep(2);
//$ssh->ping();
echo $ssh->pwd();
```
And let's also say your sshd_config file had this in it:

```
ClientAliveInterval 1
ClientAliveCountMax 1
```
At that point the SSH server would disconnect between the two `$ssh->pwd()` commands and you'd need to reset it with `$ssh->ping()`.

But is that what's actually going on in your case? idk. Outside of your stack trace I have very little information that I can work with.

In order to say more definitely I'm going to need to have the SSH logs. You can get them by doing `define('NET_SSH2_LOGGING', 2)` and then `echo $ssh->getLog()` after the error. Ideally I'd be able to see the whole SFTP exchange but if you're getting the error after you download or upload a 1GB file then I guess that's not realistic.

**Comment by sandcore-dev** [comment]
I just resolved a problem with a SFTP server using `flysystem-sftp-v3` in Laravel. Since `ping()` is mentioned, I'll post it here.

The problem was that I got a `Connection closed (by server) prematurely` exception on one third-party server, but not another, after using `allFiles()` (although any command will probably throw this.) Using the `phpseclib` SFTP class directly worked fine for both servers.

After some debugging I found out that aforementioned server disconnected after executing `ping()`. This pinging happens in the `SimpleConnectivityChecker` class. Executing `ping()` resolved the problem because it will call `reconnect()`. This worked on both third-party servers.

So I came up with this workaround:

```php
Storage::extend('sftp', function (Application $app, array $config) {
    $config['connectivityChecker'] = new class extends SimpleConnectivityChecker {
        public function isConnected(SFTP $connection): bool
        {
            if (parent::isConnected($connection)) {
                $connection->ping();
                return true;
            }

            return false;
        }
    };

    return Storage::createSftpDriver($config);
});

```

Hopefully this will help anyone.

**Comment by Naoray** [comment]
@sandcore-dev I implemented your suggestion. I think I've also found an easier implementation, by just setting the `filesystem.disks.{connectionName}.connectivityChecker` config to `new SimpleConnectivityChecker(usePing: true)`. 

However, this didn't solve my issue. Here is my stack trace of the exception starting with the `->makeDirectory()` call.

```
RuntimeException Please close the channel (256) before trying to open it again 
    vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2943 phpseclib3\Net\SSH2::open_channel
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:550 phpseclib3\Net\SFTP::partial_init_sftp_connection
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:624 phpseclib3\Net\SFTP::init_sftp_connection
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:536 phpseclib3\Net\SFTP::precheck
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2931 phpseclib3\Net\SFTP::get_xstat_cache_prop
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2902 phpseclib3\Net\SFTP::get_stat_cache_prop
    vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2668 phpseclib3\Net\SFTP::is_dir
    vendor/league/flysystem-sftp-v3/SftpAdapter.php:117 League\Flysystem\PhpseclibV3\SftpAdapter::makeDirectory
    vendor/league/flysystem-sftp-v3/SftpAdapter.php:199 League\Flysystem\PhpseclibV3\SftpAdapter::createDirectory
    vendor/league/flysystem/src/Filesystem.php:96 League\Flysystem\Filesystem::createDirectory
    vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:871 Illuminate\Filesystem\FilesystemAdapter::makeDirectory
```

The additional `ping()` goes through and opens and closes the connection, but then in the `SFTP@partial_init_sftp_connection()` the `open_channel()` causes the exception.

---

Might be a dumb question, but can a SFTP connection handle two simultaneous write requests? It's already dawning on me that if I have two processes run in the queue trying to write simultaneously to the same sftp connection, this might cause the reported error. Can someone confirm this please?

**Comment by vasilejianu** [comment]
i have the same issue with ssh and sftp after updating 
RuntimeException: Please close the channel (1) before trying to open it again in /home/vas/github/gameadmin.app/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2905
Stack trace:
#0 /home/vas/github/gameadmin.app/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2805): phpseclib3\Net\SSH2->open_channel()
#1 /home/vas/github/gameadmin.app/app/Services/Linux/GASSH.php(197): phpseclib3\Net\SSH2->exec()
#2 /home/vas/github/gameadmin.app/app/Jobs/Linux/InstallAsaServer.php(47): App\Services\Linux\GASSH->deleteUploadedScript()
#3 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\Linux\InstallAsaServer->handle()
#4 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#6 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call()
#8 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#9 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#12 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#14 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then()
#16 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#17 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#18 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\Queue\Jobs\Job->fire()
#19 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process()
#20 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob()
#21 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\Queue\Worker->daemon()
#22 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(122): Illuminate\Queue\Console\WorkCommand->runWorker()
#23 /home/vas/github/gameadmin.app/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#24 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#25 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#27 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#28 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call()
#29 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call()
#30 /home/vas/github/gameadmin.app/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#31 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run()
#32 /home/vas/github/gameadmin.app/vendor/symfony/console/Application.php(1047): Illuminate\Console\Command->run()
#33 /home/vas/github/gameadmin.app/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#34 /home/vas/github/gameadmin.app/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#35 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\Component\Console\Application->run()
#36 /home/vas/github/gameadmin.app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\Foundation\Console\Kernel->handle()
#37 /home/vas/github/gameadmin.app/artisan(13): Illuminate\Foundation\Application->handleCommand()
#38 {main}

**Comment by terrafrost** [comment]
@vasilejianu - I can reproduce your issue if I do this:

```diff
$ssh->enablePTY();
$ssh->exec('ls -latr');
$ssh->exec('ls -latr');
```
Adding these two lines will make it work better:

```diff
  $ssh->enablePTY();
  $ssh->exec('ls -latr');
+ $ssh->disablePTY();
+ $ssh->enablePTY();
  $ssh->exec('ls -latr');
```
I suppose I could make it so that if you if you try to do another `exec()` whilst in a PTY and the last `exec()` hasn't ended that it is then ended and the new one is ran. But idk if that even describes your scenario. I feel like you're probably doing a PTY but idk for sure. Can you the code that's reproducing this problem?

**Comment by vasilejianu** [comment]
hi i think the issue was here 
   $ssh = new SSH2($ipAddress, 22, 10);
i changed it to    $ssh = new SSH2($ipAddress, 22, 0); and seems to have resolved the issue
