### ISSUE TITLE
Infinite loop on`SSH2::login` command 

### ISSUE THREAD

**Issue by LordSimal** [phpseclib/phpseclib#2039]
Recently we encountered the issue, that PHPSeclib seems to cause an infinite loop when trying to login to a SFTP server.

```
#477 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4220): phpseclib3\Net\SFTP->disconnect_helper(10)
#478 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4599): phpseclib3\Net\SSH2->send_binary_packet('\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00')
#479 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3536): phpseclib3\Net\SSH2->disconnect_helper(10)
#480 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4220): phpseclib3\Net\SFTP->disconnect_helper(10)
#481 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4599): phpseclib3\Net\SSH2->send_binary_packet('\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00')
#482 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3536): phpseclib3\Net\SSH2->disconnect_helper(10)
#483 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4220): phpseclib3\Net\SFTP->disconnect_helper(10)
#484 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4599): phpseclib3\Net\SSH2->send_binary_packet('\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00')
#485 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3536): phpseclib3\Net\SSH2->disconnect_helper(10)
#486 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4220): phpseclib3\Net\SFTP->disconnect_helper(10)
#487 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4599): phpseclib3\Net\SSH2->send_binary_packet('\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00')
#488 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3536): phpseclib3\Net\SSH2->disconnect_helper(10)
#489 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4220): phpseclib3\Net\SFTP->disconnect_helper(10)
#490 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4599): phpseclib3\Net\SSH2->send_binary_packet('\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00')
#491 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3536): phpseclib3\Net\SSH2->disconnect_helper(10)
#492 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4220): phpseclib3\Net\SFTP->disconnect_helper(10)
#493 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4599): phpseclib3\Net\SSH2->send_binary_packet('\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x00')
#494 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3536): phpseclib3\Net\SSH2->disconnect_helper(10)
#495 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3538): phpseclib3\Net\SFTP->disconnect_helper(10)
#496 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3496): phpseclib3\Net\SSH2->get_binary_packet()
#497 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2423): phpseclib3\Net\SSH2->get_binary_packet_or_close()
#498 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2294): phpseclib3\Net\SSH2->login_helper('redacted_user', 'redacted_pw')
#499 /path-to-myapp/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2206): phpseclib3\Net\SSH2->sublogin('redacted_user', 'redacted_pw')
#500 /path-to-myapp/src/Utility/FTP/TypeImplementations/SFTP.php(128): phpseclib3\Net\SSH2->login('redacted_user', 'redacted_pw')
```

As you can see this stacktrace goes on for about 500 lines till xDebug breaks the infinite for me locally.

Its basically this call:
```
$sftp = new \phpseclib3\Net\SFTP($server, $port);
$sftp->login($user, $password);
```

Version: 3.0.41
PHP: 8.3.9

What kind of information do you need so you can debug this?

**Comment by LordSimal** [comment]
After updating to 3.0.42 it works again.
So https://github.com/phpseclib/phpseclib/pull/2031 was the problem.
