### ISSUE TITLE
Error on latest version with PHP 8.4

### ISSUE THREAD

**Issue by s22-tech** [phpseclib/phpseclib#2053]
After upgrading to PHP 8.4 and the latest phpseclib, I got this error:

```
PHP Fatal error:  Uncaught TypeError: stream_set_timeout(): Argument #2 ($seconds) must be of type int, string given in /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php:3275
Stack trace:
#0 /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php(3275): stream_set_timeout(Resource id #176, '60', 0)
#1 /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php(1384): phpseclib3\Net\SSH2->get_binary_packet()
#2 /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php(1253): phpseclib3\Net\SSH2->key_exchange()
#3 /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php(2001): phpseclib3\Net\SSH2->connect()
#4 /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php(1982): phpseclib3\Net\SSH2->sublogin('local')
#5 /Users/x/php/my-ip/includes/my_ip_3_functions.inc.php(132): phpseclib3\Net\SSH2->login('local', Object(phpseclib3\Crypt\RSA\PrivateKey))
#6 /Users/x/php/my-ip/my_ip_2_updater.php(205): loop_thru_servers(Array, 'xxx.xxx.xxx.xxx', Object(phpseclib3\Crypt\RSA\PrivateKey))
#7 /Users/x/php/my-ip/my_ip_1_startup.php(154): require_once('/Users/x/p...')
#8 {main}
  thrown in /Users/x/php/vendor/phpseclib3/phpseclib/Net/SSH2.php on line 3275
```
  
Changing this line in `/phpseclib3/phpseclib/Net/SSH2.php`:

```
private function get_stream_timeout()
{
	$sec = ini_get('default_socket_timeout');
```
	
to this:

```
private function get_stream_timeout()
{
	$sec = (int)ini_get('default_socket_timeout');
```
	
fixed the problem.

An alternate fix would be to adjust the return of that function, like so:
	
`return [(int)$sec, $usec];`

Both worked for me.

**Comment by terrafrost** [comment]
I guess you're using the master branch?

Anyway, https://github.com/phpseclib/phpseclib/commit/46c37561659e2311619e628d8e0676281f520328 should fix this.

Thanks!
