### ISSUE TITLE
Import / export of EC keys in "BIND" format

### ISSUE THREAD

**Issue by martenlehmann** [phpseclib/phpseclib#2054]
Hello,

I'm a bit lost in how to call the format correctly, as there doesn't seem to be an official specification about this. Yet BIND as well as PowerDNS are using this format when working with keys in the context of DNSSEC. Algorithm `13` as defined by [IANA](https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml) is a variant of ECDSA: `ECDSA Curve P-256 with SHA-256`. Among the provided [sample keys](https://github.com/isc-projects/bind9/tree/main/tests/dns/comparekeys) in the BIND repository you will find several files containing `013` in their name. For example:

`Kexample.+013+19786.private`:
```
Private-key-format: v1.3
Algorithm: 13 (ECDSAP256SHA256)
PrivateKey: ZYcYhR5f98vI1+BFGKLIrarZrqxJM4mRy9tvwntdYoo=
```

`Kexample.+013+19786.key`:
```
example. IN DNSKEY 256 3 13 S35Z1XtGlnnU7BBahMJwAZXXff+JupyIDssNfJyrugLKq5R10TJ5tU3W r3VuP6aJNs6+uL2cMPVTVT1vr1Aqwg==
```

If you remove any possible spaces within the keys (added due to the way the DNS protocol allows to split long records), it boils down to this:

```
Private Key: ZYcYhR5f98vI1+BFGKLIrarZrqxJM4mRy9tvwntdYoo=
Public Key: S35Z1XtGlnnU7BBahMJwAZXXff+JupyIDssNfJyrugLKq5R10TJ5tU3Wr3VuP6aJNs6+uL2cMPVTVT1vr1Aqwg==
```

I am able to:
- create and export private keys
- import private keys
- derive public key from private keys and export them

in this format. Unfortunately I'm only able to do this using the `ecdsa` module in Python using the `NIST256p` class (this specific curve is also called `SECP256R1` and `prime256v1`) and I'm pretty lost on how to accomplish the same using `phpseclib` in PHP after experimenting for some time.

My initial attempts looked promising:

```php
$private_key = \phpseclib3\Crypt\EC::createKey('secp256r1');
$private_key_jwk = json_decode($private_key->toString('JWK'), true);
var_dump($private_key_jwk);
$public_key = $private_key->getPublicKey();
$public_key_jwk = json_decode($public_key->toString('JWK'), true);
var_dump($public_key_jwk);
```

Output:
```
array(1) {
  ["keys"]=>
  array(1) {
    [0]=>
    array(5) {
      ["kty"]=>
      string(2) "EC"
      ["crv"]=>
      string(5) "P-256"
      ["x"]=>
      string(44) "ol86Imf3JSfuQT2iVxLJZ-5_3soPcWP47IJWnmZTHC8="
      ["y"]=>
      string(44) "ix_JR979tAQsa4f_JHLD5xgLimP4zJXOKCtAP2nqceE="
      ["d"]=>
      string(44) "ag2f2FxnVvn-jHWrC8cqy2rLm4DRuFlyEPEwWfkPX14="
    }
  }
}
array(1) {
  ["keys"]=>
  array(1) {
    [0]=>
    array(4) {
      ["kty"]=>
      string(2) "EC"
      ["crv"]=>
      string(5) "P-256"
      ["x"]=>
      string(44) "ol86Imf3JSfuQT2iVxLJZ-5_3soPcWP47IJWnmZTHC8="
      ["y"]=>
      string(44) "ix_JR979tAQsa4f_JHLD5xgLimP4zJXOKCtAP2nqceE="
    }
  }
}
```

The length of the strings look very similar to the example and as I found out by studying source code, the public key basically seems to be a base64 encoded string of the binary `x` and `y` concatenated. The `d` value is missing in the public key,so I guess it represents the private key in some way. I'm not able to import it in the `ecdsa` module though and I'm clueless how to transform it.

When I import the `JWK`-string of the private key (containing `d`, `x` and `y`) using this code, it works correctly:
```php
$private_key = \phpseclib3\Crypt\EC::loadFormat('JWK', json_encode($private_key_jwk));
```

When I remove `x`and `y` before though, so `phpseclib` is forced to derive the public key from the private like (just like the `ecdsa` module does), like this:

```php
unset(($private_key_jwk['keys'])[0]['x']);
unset(($private_key_jwk['keys'])[0]['y']);
```

an exception is thrown:

```
Fatal error:  Uncaught RuntimeException: Unable to verify that point exists on curve in /work-in-progress/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/JWK.php:91
Stack trace:
#0 /work-in-progress/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php(236): phpseclib3\Crypt\EC\Formats\Keys\JWK::load()
#1 /work-in-progress/dnssec.php(60): phpseclib3\Crypt\Common\AsymmetricKey::loadFormat()
#2 /work-in-progress/dnssec.php(97): create_private_key_ecdsa()
#3 {main}
  thrown in /work-in-progress/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/JWK.php on line 91
```

I feel like I'm not too far off, but as I'm neither an expert in cryptography nor in the `phpseclib` internals, I would be really grateful if someone could provide help.

**Comment by terrafrost** [comment]
I'll take a look at this in the next few days - got a busy next few days!

**Comment by terrafrost** [comment]
> create and export private keys

```php
$private_key = \phpseclib3\Crypt\EC::createKey('secp256r1');
$private_key_jwk = json_decode($private_key->toString('JWK'), true);
echo $private_key_jwk['keys'][0]['d'];
```

> import private keys

```php
use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Common\Functions\Strings;
use phpseclib3\Math\BigInteger;

$privateKey = 'ZYcYhR5f98vI1+BFGKLIrarZrqxJM4mRy9tvwntdYoo=';

$curve = new \phpseclib3\Crypt\EC\Curves\secp256r1();
$dA = new BigInteger(base64_decode($privateKey), 256);
$curve->rangeCheck($dA);
$QA = $curve->multiplyPoint($curve->getBasePoint(), $dA);

$privateKey = [
    'kty' => 'EC',
    'crv' => 'P-256',
    'x' => Strings::base64url_encode($QA[0]->toBytes()),
    'y' => Strings::base64url_encode($QA[1]->toBytes()),
    'd' => Strings::base64url_encode($dA->toBytes()),
];

$privateKey = json_encode(['keys' => [$privateKey]]);

$ec = PublicKeyLoader::load($privateKey);
```

> derive public key from private keys and export them

```php
use phpseclib3\Math\BigInteger;

$privateKey = 'ZYcYhR5f98vI1+BFGKLIrarZrqxJM4mRy9tvwntdYoo=';

$curve = new \phpseclib3\Crypt\EC\Curves\secp256r1();
$dA = new BigInteger(base64_decode($privateKey), 256);
$curve->rangeCheck($dA);
$QA = $curve->multiplyPoint($curve->getBasePoint(), $dA);

echo base64_encode($QA[0]->toBytes() . $QA[1]->toBytes());
```
That last one returns `S35Z1XtGlnnU7BBahMJwAZXXff+JupyIDssNfJyrugLKq5R10TJ5tU3Wr3VuP6aJNs6+uL2cMPVTVT1vr1Aqwg==` which, I note, is the same thing that's in Kexample.+013+19786.key after the spaces are removed.

**Comment by martenlehmann** [comment]
Thanks, that's excellent help! I definitely wouldn't have figured out the import part on my own any time soon 😇

These examples solved the challenge for myself and now I wonder how the knowledge could be made useful to others. Adding a key format type `BIND` similar to `JWK` seems straightforward, yet there may be little demand. These `.private` key files are created by BIND's `dnssec-keygen` and I think that's the only "specification" (the PowerDNS API calls them [Cryptokeys](https://doc.powerdns.com/authoritative/http-api/cryptokey.html) ). The file name as well as the zone snippets within the public `.key` files are relying on a specific domain name though, which may digress too much from pure cryptographic algorithms.

**Comment by terrafrost** [comment]
Apologies for the delay.

https://github.com/terrafrost/phpseclib/tree/dnssec has support for "DNSSEC" keys. I can merge it into the 3.0 branch (altho I'd like to add unit tests before I do that and fix a PHP 5.6 syntax error as well) but ideally I'd get your input before I merged it in.

If you could check it out and lmk what you think that'd be great.

Thanks!
