### ISSUE TITLE
SFTP server DisplayLogin (/etc/motd style post login message) breaks Net_SFTP::login()

### ISSUE THREAD

**Issue by palepurple** [phpseclib/phpseclib#725]
When using proftpd's SFTP server, I'm able to specify an /etc/motd style message which is shown after login (DisplayLogin config option). 

Net_SFTP does support a Banner style message, but it doen't seem to support a after-login-message.

A command line 'sftp' client (via openssh 1:6.7p1-5) is able to login without issue.
   
When the authentication requests are made, the server logs them as being successful, but \NetSFTP::login() is not returning true.

Rummaging through the code a little, it looks like a NET_SSH2_MSG_CHANNEL_EXTENDED_DATA type packet is coming back which confuses Net_SSH2::_get_channel_packet($client_channel, $skip_extended = false) { ... } (around line: 3046 of SSH2.php on master ...).

    $ sftp -P 2222 testsftpz70@testsftpz92.example.com
    testsftpz70@testsftpz92.example.com's password: 
    Hello world. <- troublesome message!
    Connected to testsftpz92.example.com.
    sftp> 
   
code wise :

    $sftp = new \phpseclib\Net\SFTP($hostname, 2222);
    $ok = $sftp->login($username, $password); 
    // $ok == false

or

   $sftp = new Net_SFTP($hostname, 2222);
   $ok = $sftp->login($username, $password); 
   // $ok == false

I've tested this against 0.3.* releases, and also modified the code to run against master ( 8cad45cd6b9711ec69a982d1485bddc01da3fadd ) and it still seems to misbehave in the same way.

**Comment by terrafrost** [comment]
Well it's not an issue with SSH-2.0-OpenSSH_6.7p1 Ubuntu-5ubuntu1. I edited the /etc/motd file, set PrintMotd to yes in /etc/ssh/sshd_config and restarted OpenSSH and was able to see the MOTD just fine with the following:

```php
<?php
include('Net/SSH2.php');

$ssh = new Net_SSH2('127.0.0.1', 4022);
$ssh->login('ubuntu', 'big1word');
$ssh->setTimeout(2);
echo $ssh->read();
```
So that establishes that the MOTD is working. When I SFTP in I don't see the MOTD at all. Not even in the log files do I see it being sent. Which makes sense since SFTP doesn't really provide a mechanism for extraneous information like that to be sent. SSH provides for a banner message to be sent (as your post notes) but that's distinct from the MOTD.

I am also unable to install proftp via apt-get via Ubuntu. http://www.liquidweb.com/kb/how-to-install-and-configure-proftpd-on-ubuntu-14-04-lts/ suggests that on 14.04 I should be able to do `sudo apt-get install proftpd` but that doesn't work.

In lieu of that...  can you get me log files?

**Comment by xaled1** [comment]
Having the same issue here.
PHP Fatal error:  Uncaught RuntimeException: Unable to fulfill channel request in /opt/openpda/client/phpseclib/Net/SSH2.php:3675
Stack trace:
#0 /opt/openpda/client/phpseclib/Net/SFTP.php(452): phpseclib\Net\SSH2->get_channel_packet(256)
#1 /opt/openpda/client/pda_test_sftp1.php(47): phpseclib\Net\SFTP->login('Dott', Object(phpseclib\Crypt\RSA))
#2 {main}
  thrown in /opt/openpda/client/phpseclib/Net/SSH2.php on line 3675

Trace is equal to:
http://webcache.googleusercontent.com/search?q=cache:TKNFGczN7jQJ:techqa.info/programming/tag/pty%3Fafter%3D25167721+&cd=1&hl=de&ct=clnk&gl=de&client=firefox-b

search for NET_SSH2_MSG_CHANNEL_EXTENDED_DATA

**Comment by terrafrost** [comment]
What version of phpseclib are you using? The cache'd Google thing is from 2015. phpseclib has had quite a few releases since then.

Also, any particular reason why you can't post your own log files? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `echo $ssh->getLog();`.

**Comment by Castaglia** [comment]
Reading through https://github.com/phpseclib/phpseclib/issues/1199#issuecomment-340961555 as well as this issue, I would like to point out that https://datatracker.ietf.org/doc/html/rfc4254#section-5.2 _does_ mention the use of `SSH_MSG_CHANNEL_EXTENDED_DATA` for stderr for "interactive sessions":
```
   Additionally, some channels can transfer several types of data.  An
   example of this is stderr data from interactive sessions.  Such data
   can be passed with SSH_MSG_CHANNEL_EXTENDED_DATA messages, where a
   separate integer specifies the type of data.  The available types and
   their interpretation depend on the type of channel.

      byte      SSH_MSG_CHANNEL_EXTENDED_DATA
      uint32    recipient channel
      uint32    data_type_code
      string    data

   Data sent with these messages consumes the same window as ordinary
   data.

   Currently, only the following type is defined.  Note that the value
   for the 'data_type_code' is given in decimal format for readability,
   but the values are actually uint32 values.

               Symbolic name                  data_type_code
               -------------                  --------------
             SSH_EXTENDED_DATA_STDERR               1
```
What is not clear is whether the SFTP subsystem channel would be considered/treated as one of these "interactive sessions".  Just FYI.
